# Verified Agricultural Seed Data and Official Source Registry (Phase 3A.2 Knowledge Base Dataset)

from __future__ import annotations

import logging
from typing import Any, Dict, List
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

SEED_SOURCES = [{'document_identifier': 'ICAR-IIPR-PUB-2024-01',
  'id': 'src_icar_iipr',
  'organization': 'ICAR - Indian Institute of Pulses Research (IIPR)',
  'publication_year': 2024,
  'source_scope': 'NATIONAL',
  'source_title': 'Pulse Production Technologies & Zaid Crop Guidelines',
  'tier': 'TIER_1_ICAR',
  'url': 'https://iipr.icar.gov.in',
  'verification_status': 'VERIFIED'},
 {'document_identifier': 'PAU-POP-KHARIF-2024',
  'id': 'src_pau_ludhiana',
  'organization': 'Punjab Agricultural University (PAU), Ludhiana',
  'publication_year': 2024,
  'source_scope': 'STATE',
  'source_title': 'Package of Practices for Crops of Punjab - Kharif & Summer',
  'tier': 'TIER_4_SAU',
  'url': 'https://www.pau.edu',
  'verification_status': 'VERIFIED'},
 {'document_identifier': 'UP-ZAID-GUIDELINE-2024',
  'id': 'src_up_agri',
  'organization': 'Department of Agriculture, Uttar Pradesh',
  'publication_year': 2024,
  'source_scope': 'STATE',
  'source_title': 'Zaid Crop Advisory & District Crop Sowing Schedule',
  'tier': 'TIER_3_STATE_GOV',
  'url': 'https://upagriparakh.gov.in',
  'verification_status': 'VERIFIED'},
 {'document_identifier': 'TNAU-AGRI-PULSES-2023',
  'id': 'src_tnau',
  'organization': 'Tamil Nadu Agricultural University (TNAU)',
  'publication_year': 2023,
  'source_scope': 'STATE',
  'source_title': 'Rice Fallow Pulses Agritech Advisory',
  'tier': 'TIER_4_SAU',
  'url': 'https://agritech.tnau.ac.in',
  'verification_status': 'VERIFIED'},
 {'document_identifier': 'SK-DEMO-2026',
  'id': 'src_demo_fallback',
  'organization': 'SmartKisan Development Baseline Data',
  'publication_year': 2026,
  'source_scope': 'DEVELOPMENT_DEMO',
  'source_title': 'Development Fallback Agronomic Estimates',
  'tier': 'DEVELOPMENT_DEMO',
  'url': None,
  'verification_status': 'DEVELOPMENT_DEMO'},
 {'document_identifier': 'ICAR-IARI-POP-2024',
  'id': 'src_icar_iari',
  'notes': 'Pusa national crop handbook',
  'organization': 'ICAR - Indian Agricultural Research Institute (IARI)',
  'publication_year': 2024,
  'source_title': 'Package of Practices for Field Crops',
  'source_type': 'ICAR_IARI',
  'tier': 'TIER_1_ICAR',
  'url': 'https://iari.icar.gov.in',
  'verification_status': 'VERIFIED'},
 {'document_identifier': 'ICAR-IIHR-HORT-2024',
  'id': 'src_icar_iihr',
  'notes': 'Authoritative guide for fruit and vegetable crops',
  'organization': 'ICAR - Indian Institute of Horticultural Research (IIHR)',
  'publication_year': 2024,
  'source_title': 'Horticultural & Cucurbit Crops Package of Practices',
  'source_type': 'ICAR_IIHR',
  'tier': 'TIER_1_ICAR',
  'url': 'https://iihr.icar.gov.in',
  'verification_status': 'VERIFIED'},
 {'document_identifier': 'ICAR-CRIDA-CONTINGENCY-2024',
  'id': 'src_icar_crida',
  'notes': 'Agromet and weather contingency guidance',
  'organization': 'ICAR - Central Research Institute for Dryland Agriculture (CRIDA)',
  'publication_year': 2024,
  'source_title': 'District Agriculture Contingency Plans & Weather Thresholds',
  'source_type': 'ICAR_CRIDA',
  'tier': 'TIER_1_ICAR',
  'url': 'http://www.crida.in',
  'verification_status': 'VERIFIED'},
 {'document_identifier': 'AGMARKNET-PRICE-2024',
  'id': 'src_agmarknet',
  'notes': 'Official mandi price and yield economics data',
  'organization': 'AGMARKNET / Ministry of Agriculture & Farmers Welfare, GOI',
  'publication_year': 2024,
  'source_title': 'Official Market Price & Cultivation Economics Data',
  'source_type': 'OFFICIAL_MARKET_DATA',
  'tier': 'TIER_2_GOI',
  'url': 'https://agmarknet.gov.in',
  'verification_status': 'VERIFIED'}]

SEED_CROP_CATALOG = [{'active': True,
  'category': 'Pulse',
  'code': 'summer_moong',
  'crop_name': 'Summer Moong',
  'description': 'Short-duration pulse crop ideal for gap windows between Rabi Wheat and Kharif Paddy.',
  'expected_yield_qtl_per_acre': 4.5,
  'growth_habit': 'Annual',
  'hindi_name': 'समर मूंग',
  'investment_per_acre': 6500,
  'is_gap_candidate': True,
  'is_legume': True,
  'market_price_per_quintal': 8550,
  'max_duration_days': 65,
  'min_duration_days': 55,
  'net_profit_per_acre_max': 30000,
  'net_profit_per_acre_min': 22000,
  'scientific_name': 'Vigna radiata',
  'season': 'Zaid / Summer',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Low'},
 {'active': True,
  'category': 'Pulse',
  'code': 'summer_urad',
  'crop_name': 'Summer Urad',
  'description': 'Short-duration leguminous gap pulse crop.',
  'expected_yield_qtl_per_acre': 4.0,
  'growth_habit': 'Annual',
  'hindi_name': 'समर उड़द',
  'investment_per_acre': 7000,
  'is_gap_candidate': True,
  'is_legume': True,
  'market_price_per_quintal': 7400,
  'max_duration_days': 70,
  'min_duration_days': 60,
  'net_profit_per_acre_max': 25000,
  'net_profit_per_acre_min': 18000,
  'scientific_name': 'Vigna mungo',
  'season': 'Zaid / Summer',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Low'},
 {'active': True,
  'category': 'Pulse / Vegetable',
  'code': 'cowpea',
  'crop_name': 'Cowpea (Lobia)',
  'description': 'Dual-purpose vegetable and green manure leguminous pulse crop.',
  'expected_yield_qtl_per_acre': 5.0,
  'growth_habit': 'Annual',
  'hindi_name': 'लोबिया / बोड़ा',
  'investment_per_acre': 6000,
  'is_gap_candidate': True,
  'is_legume': True,
  'market_price_per_quintal': 5500,
  'max_duration_days': 60,
  'min_duration_days': 50,
  'net_profit_per_acre_max': 22000,
  'net_profit_per_acre_min': 15000,
  'scientific_name': 'Vigna unguiculata',
  'season': 'Zaid / Summer',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Low-Moderate'},
 {'active': True,
  'category': 'Oilseed',
  'code': 'summer_sesame',
  'crop_name': 'Summer Sesame (Til)',
  'description': 'High-value short duration oilseed for extended gap windows (75+ days).',
  'expected_yield_qtl_per_acre': 3.0,
  'growth_habit': 'Annual',
  'hindi_name': 'समर तिल',
  'investment_per_acre': 5500,
  'is_gap_candidate': True,
  'is_legume': False,
  'market_price_per_quintal': 14500,
  'max_duration_days': 85,
  'min_duration_days': 75,
  'net_profit_per_acre_max': 28000,
  'net_profit_per_acre_min': 20000,
  'scientific_name': 'Sesamum indicum',
  'season': 'Zaid / Summer',
  'verification_status': 'PENDING_VERIFICATION',
  'water_requirement': 'Low'},
 {'active': True,
  'category': 'Fodder',
  'code': 'fodder_maize',
  'crop_name': 'Fodder Maize',
  'description': 'Ultra-short green fodder crop for livestock farmers.',
  'expected_yield_qtl_per_acre': 150.0,
  'growth_habit': 'Annual',
  'hindi_name': 'चारा मक्का',
  'investment_per_acre': 5000,
  'is_gap_candidate': True,
  'is_legume': False,
  'market_price_per_quintal': 220,
  'max_duration_days': 55,
  'min_duration_days': 45,
  'net_profit_per_acre_max': 18000,
  'net_profit_per_acre_min': 12000,
  'scientific_name': 'Zea mays (Fodder)',
  'season': 'Zaid / Summer',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Moderate'},
 {'active': True,
  'category': 'Cereal',
  'code': 'paddy',
  'crop_name': 'Paddy / Rice (Main Crop)',
  'description': 'Main Kharif cereal crop (Excluded from short gap recommendations).',
  'expected_yield_qtl_per_acre': 22.0,
  'growth_habit': 'Annual',
  'hindi_name': 'धान (मुख्य फसल)',
  'investment_per_acre': 15000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 2183,
  'max_duration_days': 150,
  'min_duration_days': 120,
  'net_profit_per_acre_max': 38000,
  'net_profit_per_acre_min': 25000,
  'scientific_name': 'Oryza sativa',
  'season': 'Kharif',
  'verification_status': 'VERIFIED',
  'water_requirement': 'High'},
 {'active': True,
  'category': 'Cash Crop',
  'code': 'sugarcane',
  'crop_name': 'Sugarcane',
  'description': 'Long duration cash crop (Excluded from short gap recommendations).',
  'expected_yield_qtl_per_acre': 350.0,
  'growth_habit': 'Perennial',
  'hindi_name': 'गन्ना (दीर्घकालिक फसल)',
  'investment_per_acre': 30000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 355,
  'max_duration_days': 365,
  'min_duration_days': 300,
  'net_profit_per_acre_max': 80000,
  'net_profit_per_acre_min': 50000,
  'scientific_name': 'Saccharum officinarum',
  'season': 'Perennial',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Very High'},
 {'category': 'Pulse',
  'code': 'chana',
  'crop_name': 'Gram (Chana)',
  'description': 'Major Rabi pulse crop grown extensively in dryland and irrigated regions.',
  'expected_yield_qtl_per_acre': 7.0,
  'growth_habit': 'Annual',
  'hindi_name': 'चना',
  'investment_per_acre': 8500,
  'is_gap_candidate': False,
  'is_legume': True,
  'market_price_per_quintal': 5440,
  'max_duration_days': 110,
  'min_duration_days': 90,
  'net_profit_per_acre_max': 38000,
  'net_profit_per_acre_min': 25000,
  'scientific_name': 'Cicer arietinum',
  'season': 'Rabi',
  'sub_category': 'Rabi Pulse',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Low'},
 {'category': 'Pulse',
  'code': 'arhar',
  'crop_name': 'Arhar (Pigeonpea)',
  'description': 'Important Kharif pulse crop deep-rooting and improving soil structure.',
  'expected_yield_qtl_per_acre': 6.5,
  'growth_habit': 'Annual',
  'hindi_name': 'अरहर / तुअर',
  'investment_per_acre': 9000,
  'is_gap_candidate': False,
  'is_legume': True,
  'market_price_per_quintal': 7000,
  'max_duration_days': 160,
  'min_duration_days': 130,
  'net_profit_per_acre_max': 35000,
  'net_profit_per_acre_min': 22000,
  'scientific_name': 'Cajanus cajan',
  'season': 'Kharif',
  'sub_category': 'Kharif Pulse',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Oilseed',
  'code': 'mustard',
  'crop_name': 'Mustard (Sarson)',
  'description': 'Primary Rabi oilseed crop in northern plains.',
  'expected_yield_qtl_per_acre': 8.0,
  'growth_habit': 'Annual',
  'hindi_name': 'सरसों',
  'investment_per_acre': 8000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 5650,
  'max_duration_days': 115,
  'min_duration_days': 100,
  'net_profit_per_acre_max': 42000,
  'net_profit_per_acre_min': 28000,
  'scientific_name': 'Brassica juncea',
  'season': 'Rabi',
  'sub_category': 'Rabi Oilseed',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Low'},
 {'category': 'Cereal',
  'code': 'maize',
  'crop_name': 'Maize (Corn)',
  'description': 'Versatile cereal crop grown for grain, feed, and industrial use.',
  'expected_yield_qtl_per_acre': 18.0,
  'growth_habit': 'Annual',
  'hindi_name': 'मक्का',
  'investment_per_acre': 11000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 2225,
  'max_duration_days': 105,
  'min_duration_days': 85,
  'net_profit_per_acre_max': 34000,
  'net_profit_per_acre_min': 22000,
  'scientific_name': 'Zea mays',
  'season': 'Kharif',
  'sub_category': 'Coarse Cereal',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Cereal',
  'code': 'rabi_wheat',
  'crop_name': 'Wheat',
  'description': 'Staple Rabi cereal crop cultivated extensively across Indo-Gangetic plains.',
  'expected_yield_qtl_per_acre': 18.0,
  'growth_habit': 'Annual',
  'hindi_name': 'गेहूं',
  'investment_per_acre': 12500,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 2420,
  'max_duration_days': 135,
  'min_duration_days': 115,
  'net_profit_per_acre_max': 38000,
  'net_profit_per_acre_min': 24000,
  'scientific_name': 'Triticum aestivum',
  'season': 'Rabi',
  'sub_category': 'Main Grain Cereal',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Vegetable',
  'code': 'tomato',
  'crop_name': 'Tomato',
  'description': 'High-value commercial vegetable crop with high market demand.',
  'expected_yield_qtl_per_acre': 110.0,
  'growth_habit': 'Annual',
  'hindi_name': 'टमाटर',
  'investment_per_acre': 22000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 1800,
  'max_duration_days': 100,
  'min_duration_days': 80,
  'net_profit_per_acre_max': 75000,
  'net_profit_per_acre_min': 35000,
  'scientific_name': 'Solanum lycopersicum',
  'season': 'Kharif / Rabi',
  'sub_category': 'Solanaceous Vegetable',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Vegetable',
  'code': 'potato',
  'crop_name': 'Potato',
  'description': 'Major Rabi tuber vegetable crop stored extensively in cold storage.',
  'expected_yield_qtl_per_acre': 100.0,
  'growth_habit': 'Annual',
  'hindi_name': 'आलू',
  'investment_per_acre': 25000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 1200,
  'max_duration_days': 105,
  'min_duration_days': 85,
  'net_profit_per_acre_max': 65000,
  'net_profit_per_acre_min': 30000,
  'scientific_name': 'Solanum tuberosum',
  'season': 'Rabi',
  'sub_category': 'Tuber Vegetable',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Vegetable',
  'code': 'onion',
  'crop_name': 'Onion',
  'description': 'Essential commercial bulb vegetable crop.',
  'expected_yield_qtl_per_acre': 90.0,
  'growth_habit': 'Annual',
  'hindi_name': 'प्याज',
  'investment_per_acre': 20000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 2200,
  'max_duration_days': 120,
  'min_duration_days': 100,
  'net_profit_per_acre_max': 70000,
  'net_profit_per_acre_min': 30000,
  'scientific_name': 'Allium cepa',
  'season': 'Rabi / Kharif',
  'sub_category': 'Bulb Vegetable',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Vegetable',
  'code': 'okra',
  'crop_name': 'Okra (Bhindi)',
  'description': 'Quick-yielding summer vegetable crop suitable for Zaid season.',
  'expected_yield_qtl_per_acre': 45.0,
  'growth_habit': 'Annual',
  'hindi_name': 'भिंडी',
  'investment_per_acre': 12000,
  'is_gap_candidate': True,
  'is_legume': False,
  'market_price_per_quintal': 2400,
  'max_duration_days': 75,
  'min_duration_days': 60,
  'net_profit_per_acre_max': 45000,
  'net_profit_per_acre_min': 25000,
  'scientific_name': 'Abelmoschus esculentus',
  'season': 'Zaid / Summer',
  'sub_category': 'Summer Vegetable',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Fruit',
  'code': 'watermelon',
  'crop_name': 'Watermelon',
  'description': 'High-demand summer cucurbit fruit crop grown in sandy loam soils.',
  'expected_yield_qtl_per_acre': 150.0,
  'growth_habit': 'Annual Vine',
  'hindi_name': 'तरबूज',
  'investment_per_acre': 18000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 1100,
  'max_duration_days': 95,
  'min_duration_days': 80,
  'net_profit_per_acre_max': 85000,
  'net_profit_per_acre_min': 40000,
  'scientific_name': 'Citrullus lanatus',
  'season': 'Zaid / Summer',
  'sub_category': 'Cucurbit Fruit',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'},
 {'category': 'Fruit',
  'code': 'muskmelon',
  'crop_name': 'Muskmelon (Kharbooza)',
  'description': 'Commercial Zaid fruit crop requiring warm dry weather during maturity.',
  'expected_yield_qtl_per_acre': 100.0,
  'growth_habit': 'Annual Vine',
  'hindi_name': 'खरबूजा',
  'investment_per_acre': 16000,
  'is_gap_candidate': False,
  'is_legume': False,
  'market_price_per_quintal': 1400,
  'max_duration_days': 90,
  'min_duration_days': 75,
  'net_profit_per_acre_max': 70000,
  'net_profit_per_acre_min': 35000,
  'scientific_name': 'Cucumis melo',
  'season': 'Zaid / Summer',
  'sub_category': 'Cucurbit Fruit',
  'verification_status': 'VERIFIED',
  'water_requirement': 'Medium'}]

SEED_AGRONOMIC_PROFILES = [
    {
        'crop_code': 'rabi_wheat',
        'temperature_min_c': 10.0,
        'temperature_optimal_min_c': 15.0,
        'temperature_optimal_max_c': 22.0,
        'temperature_max_c': 28.0,
        'rainfall_min_mm': 350.0,
        'rainfall_optimal_min_mm': 400.0,
        'rainfall_optimal_max_mm': 500.0,
        'soil_types': ['Loamy', 'Clay Loam', 'Alluvial'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.5,
        'water_requirement': 'Medium',
        'irrigation_requirement': '4-5 Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Moderate',
        'heat_sensitivity': 'High',
        'sowing_window': 'Nov 1 - Nov 25',
        'harvest_window': 'Mar 25 - Apr 20',
        'source_id': 'src_icar_iari',
    },
    {
        'crop_code': 'paddy',
        'temperature_min_c': 20.0,
        'temperature_optimal_min_c': 25.0,
        'temperature_optimal_max_c': 35.0,
        'temperature_max_c': 40.0,
        'rainfall_min_mm': 1000.0,
        'rainfall_optimal_min_mm': 1200.0,
        'rainfall_optimal_max_mm': 1500.0,
        'soil_types': ['Clay', 'Clay Loam', 'Alluvial'],
        'soil_ph_min': 5.5,
        'soil_ph_max': 7.0,
        'water_requirement': 'High',
        'irrigation_requirement': 'Standing Water / Canal',
        'waterlogging_tolerance': 'High',
        'drought_tolerance': 'Low',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Jun 15 - Jul 15',
        'harvest_window': 'Oct 15 - Nov 15',
        'source_id': 'src_icar_iari',
    },
    {
        'crop_code': 'summer_moong',
        'temperature_min_c': 20.0,
        'temperature_optimal_min_c': 25.0,
        'temperature_optimal_max_c': 35.0,
        'temperature_max_c': 42.0,
        'rainfall_min_mm': 250.0,
        'rainfall_optimal_min_mm': 300.0,
        'rainfall_optimal_max_mm': 450.0,
        'soil_types': ['Sandy Loam', 'Loamy'],
        'soil_ph_min': 6.2,
        'soil_ph_max': 7.8,
        'water_requirement': 'Low',
        'irrigation_requirement': '2-3 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'High',
        'heat_sensitivity': 'Low',
        'sowing_window': 'Mar 15 - Apr 15',
        'harvest_window': 'May 25 - Jun 15',
        'source_id': 'src_icar_iipr',
    },
    {
        'crop_code': 'summer_urad',
        'temperature_min_c': 20.0,
        'temperature_optimal_min_c': 25.0,
        'temperature_optimal_max_c': 35.0,
        'temperature_max_c': 40.0,
        'rainfall_min_mm': 250.0,
        'rainfall_optimal_min_mm': 300.0,
        'rainfall_optimal_max_mm': 450.0,
        'soil_types': ['Sandy Loam', 'Loamy'],
        'soil_ph_min': 6.2,
        'soil_ph_max': 7.5,
        'water_requirement': 'Low',
        'irrigation_requirement': '2-3 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'High',
        'heat_sensitivity': 'Low',
        'sowing_window': 'Mar 15 - Apr 15',
        'harvest_window': 'May 25 - Jun 20',
        'source_id': 'src_icar_iipr',
    },
    {
        'crop_code': 'cowpea',
        'temperature_min_c': 20.0,
        'temperature_optimal_min_c': 24.0,
        'temperature_optimal_max_c': 32.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 250.0,
        'rainfall_optimal_min_mm': 300.0,
        'rainfall_optimal_max_mm': 500.0,
        'soil_types': ['Sandy Loam', 'Loamy'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.5,
        'water_requirement': 'Low',
        'irrigation_requirement': '2-3 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'High',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Feb 20 - Apr 10',
        'harvest_window': 'May 1 - Jun 15',
        'source_id': 'src_icar_iipr',
    },
    {
        'crop_code': 'chana',
        'temperature_min_c': 10.0,
        'temperature_optimal_min_c': 15.0,
        'temperature_optimal_max_c': 25.0,
        'temperature_max_c': 30.0,
        'rainfall_min_mm': 250.0,
        'rainfall_optimal_min_mm': 300.0,
        'rainfall_optimal_max_mm': 400.0,
        'soil_types': ['Sandy Loam', 'Loamy', 'Clay Loam'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 8.0,
        'water_requirement': 'Low',
        'irrigation_requirement': '1-2 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'High',
        'heat_sensitivity': 'High',
        'sowing_window': 'Oct 15 - Nov 15',
        'harvest_window': 'Mar 1 - Mar 30',
        'source_id': 'src_icar_iipr',
    },
    {
        'crop_code': 'arhar',
        'temperature_min_c': 15.0,
        'temperature_optimal_min_c': 20.0,
        'temperature_optimal_max_c': 30.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 600.0,
        'rainfall_optimal_min_mm': 750.0,
        'rainfall_optimal_max_mm': 1000.0,
        'soil_types': ['Deep Loamy', 'Clay Loam'],
        'soil_ph_min': 6.5,
        'soil_ph_max': 7.8,
        'water_requirement': 'Medium',
        'irrigation_requirement': '1-2 Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'High',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Jun 15 - Jul 15',
        'harvest_window': 'Nov 20 - Jan 15',
        'source_id': 'src_icar_iipr',
    },
    {
        'crop_code': 'summer_sesame',
        'temperature_min_c': 22.0,
        'temperature_optimal_min_c': 25.0,
        'temperature_optimal_max_c': 35.0,
        'temperature_max_c': 40.0,
        'rainfall_min_mm': 200.0,
        'rainfall_optimal_min_mm': 250.0,
        'rainfall_optimal_max_mm': 400.0,
        'soil_types': ['Sandy Loam', 'Loamy'],
        'soil_ph_min': 5.5,
        'soil_ph_max': 8.0,
        'water_requirement': 'Low',
        'irrigation_requirement': '2-3 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'High',
        'heat_sensitivity': 'Low',
        'sowing_window': 'Feb 15 - Mar 30',
        'harvest_window': 'May 15 - Jun 25',
        'source_id': 'src_tnau',
    },
    {
        'crop_code': 'mustard',
        'temperature_min_c': 10.0,
        'temperature_optimal_min_c': 15.0,
        'temperature_optimal_max_c': 22.0,
        'temperature_max_c': 28.0,
        'rainfall_min_mm': 250.0,
        'rainfall_optimal_min_mm': 300.0,
        'rainfall_optimal_max_mm': 400.0,
        'soil_types': ['Loamy', 'Sandy Loam'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.5,
        'water_requirement': 'Low',
        'irrigation_requirement': '2 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Moderate',
        'heat_sensitivity': 'High',
        'sowing_window': 'Oct 1 - Oct 25',
        'harvest_window': 'Feb 15 - Mar 15',
        'source_id': 'src_pau_ludhiana',
    },
    {
        'crop_code': 'fodder_maize',
        'temperature_min_c': 18.0,
        'temperature_optimal_min_c': 22.0,
        'temperature_optimal_max_c': 32.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 300.0,
        'rainfall_optimal_min_mm': 400.0,
        'rainfall_optimal_max_mm': 600.0,
        'soil_types': ['Loamy', 'Clay Loam'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.5,
        'water_requirement': 'Medium',
        'irrigation_requirement': '3-4 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Moderate',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Mar 1 - Apr 20',
        'harvest_window': 'Apr 20 - Jun 10',
        'source_id': 'src_icar_iari',
    },
    {
        'crop_code': 'maize',
        'temperature_min_c': 15.0,
        'temperature_optimal_min_c': 21.0,
        'temperature_optimal_max_c': 30.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 500.0,
        'rainfall_optimal_min_mm': 600.0,
        'rainfall_optimal_max_mm': 800.0,
        'soil_types': ['Loamy', 'Sandy Loam'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.5,
        'water_requirement': 'Medium',
        'irrigation_requirement': '4-5 Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Moderate',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Jun 15 - Jul 15 / Oct 15 - Nov 15',
        'harvest_window': 'Sep 20 - Oct 30 / Feb 15 - Mar 30',
        'source_id': 'src_icar_iari',
    },
    {
        'crop_code': 'sugarcane',
        'temperature_min_c': 15.0,
        'temperature_optimal_min_c': 24.0,
        'temperature_optimal_max_c': 32.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 1100.0,
        'rainfall_optimal_min_mm': 1300.0,
        'rainfall_optimal_max_mm': 1500.0,
        'soil_types': ['Deep Loamy', 'Clay Loam'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.5,
        'water_requirement': 'High',
        'irrigation_requirement': '8-10 Irrigations',
        'waterlogging_tolerance': 'Moderate',
        'drought_tolerance': 'Low',
        'heat_sensitivity': 'Low',
        'sowing_window': 'Feb 1 - Mar 30 / Oct 15 - Nov 30',
        'harvest_window': 'Jan 1 - Mar 30',
        'source_id': 'src_up_agri',
    },
    {
        'crop_code': 'tomato',
        'temperature_min_c': 15.0,
        'temperature_optimal_min_c': 20.0,
        'temperature_optimal_max_c': 28.0,
        'temperature_max_c': 35.0,
        'rainfall_min_mm': 400.0,
        'rainfall_optimal_min_mm': 500.0,
        'rainfall_optimal_max_mm': 600.0,
        'soil_types': ['Loamy', 'Sandy Loam'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.0,
        'water_requirement': 'Medium',
        'irrigation_requirement': 'Drip / Ridge',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Low',
        'heat_sensitivity': 'High',
        'sowing_window': 'Aug 15 - Sep 15 (Kharif) / Oct 15 - Nov 15 (Rabi)',
        'harvest_window': 'Nov 15 - Jan 15 / Feb 15 - Apr 15',
        'source_id': 'src_icar_iihr',
    },
    {
        'crop_code': 'potato',
        'temperature_min_c': 10.0,
        'temperature_optimal_min_c': 15.0,
        'temperature_optimal_max_c': 20.0,
        'temperature_max_c': 25.0,
        'rainfall_min_mm': 350.0,
        'rainfall_optimal_min_mm': 400.0,
        'rainfall_optimal_max_mm': 500.0,
        'soil_types': ['Sandy Loam', 'Loose Loam'],
        'soil_ph_min': 5.2,
        'soil_ph_max': 6.5,
        'water_requirement': 'Medium',
        'irrigation_requirement': '4-5 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Low',
        'heat_sensitivity': 'High',
        'sowing_window': 'Oct 15 - Nov 10',
        'harvest_window': 'Jan 25 - Mar 10',
        'source_id': 'src_up_agri',
    },
    {
        'crop_code': 'onion',
        'temperature_min_c': 12.0,
        'temperature_optimal_min_c': 15.0,
        'temperature_optimal_max_c': 25.0,
        'temperature_max_c': 32.0,
        'rainfall_min_mm': 350.0,
        'rainfall_optimal_min_mm': 400.0,
        'rainfall_optimal_max_mm': 550.0,
        'soil_types': ['Sandy Loam', 'Loamy'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.5,
        'water_requirement': 'Medium',
        'irrigation_requirement': '10-12 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Low',
        'heat_sensitivity': 'High',
        'sowing_window': 'Oct 15 - Nov 15 / Jun 15 - Jul 15',
        'harvest_window': 'Feb 15 - Apr 15 / Oct 15 - Dec 15',
        'source_id': 'src_icar_iihr',
    },
    {
        'crop_code': 'okra',
        'temperature_min_c': 20.0,
        'temperature_optimal_min_c': 24.0,
        'temperature_optimal_max_c': 30.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 300.0,
        'rainfall_optimal_min_mm': 350.0,
        'rainfall_optimal_max_mm': 500.0,
        'soil_types': ['Loamy', 'Sandy Loam'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 6.8,
        'water_requirement': 'Medium',
        'irrigation_requirement': '5-6 Light Irrigations',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Low',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Feb 15 - Mar 30 / Jun 15 - Jul 15',
        'harvest_window': 'May 1 - Jun 30 / Aug 15 - Oct 15',
        'source_id': 'src_icar_iihr',
    },
    {
        'crop_code': 'watermelon',
        'temperature_min_c': 20.0,
        'temperature_optimal_min_c': 24.0,
        'temperature_optimal_max_c': 32.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 250.0,
        'rainfall_optimal_min_mm': 300.0,
        'rainfall_optimal_max_mm': 400.0,
        'soil_types': ['Sandy Loam', 'Alluvial Riverbed'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.0,
        'water_requirement': 'Medium',
        'irrigation_requirement': 'Frequent Drip / Furrow',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Moderate',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Feb 15 - Mar 20',
        'harvest_window': 'May 15 - Jun 20',
        'source_id': 'src_icar_iihr',
    },
    {
        'crop_code': 'muskmelon',
        'temperature_min_c': 20.0,
        'temperature_optimal_min_c': 24.0,
        'temperature_optimal_max_c': 32.0,
        'temperature_max_c': 38.0,
        'rainfall_min_mm': 250.0,
        'rainfall_optimal_min_mm': 300.0,
        'rainfall_optimal_max_mm': 400.0,
        'soil_types': ['Sandy Loam', 'Alluvial Riverbed'],
        'soil_ph_min': 6.0,
        'soil_ph_max': 7.0,
        'water_requirement': 'Medium',
        'irrigation_requirement': 'Frequent Drip / Furrow',
        'waterlogging_tolerance': 'Sensitive',
        'drought_tolerance': 'Moderate',
        'heat_sensitivity': 'Moderate',
        'sowing_window': 'Feb 15 - Mar 20',
        'harvest_window': 'May 10 - Jun 15',
        'source_id': 'src_icar_iihr',
    },
]

SEED_REGIONAL_PROFILES = [
    # Watermelon
    {'crop_code': 'watermelon', 'state_name': 'Uttar Pradesh', 'district_name': 'Ghaziabad', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Zaid / Summer', 'sowing_start_month': 2, 'sowing_end_month': 4, 'harvest_start_month': 5, 'harvest_end_month': 6, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well / Drip', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'Optimal warm dry weather and sandy loam riverbeds', 'source_id': 'src_up_agri'},
    {'crop_code': 'watermelon', 'state_name': 'Punjab', 'district_name': 'Ludhiana', 'agro_climatic_zone': 'Trans-Gangetic Plain Zone', 'season': 'Zaid / Summer', 'sowing_start_month': 2, 'sowing_end_month': 3, 'harvest_start_month': 5, 'harvest_end_month': 6, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well / Drip', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'PAU recommended Zaid cultivation package', 'source_id': 'src_pau_ludhiana'},
    {'crop_code': 'watermelon', 'state_name': 'Jammu & Kashmir', 'district_name': None, 'agro_climatic_zone': 'Western Himalayan Zone', 'season': 'Winter', 'sowing_start_month': 11, 'sowing_end_month': 12, 'harvest_start_month': 3, 'harvest_end_month': 4, 'soil_suitability': 'Low', 'irrigation_suitability': 'Unsuitable', 'regional_suitability': 'NOT_SUITABLE', 'status': 'Active', 'reason': 'Severe frost and low soil temperature below 15°C threshold', 'source_id': 'src_icar_iihr'},
    {'crop_code': 'watermelon', 'state_name': 'Kerala', 'district_name': None, 'agro_climatic_zone': 'West Coast Plains Zone', 'season': 'Kharif', 'sowing_start_month': 6, 'sowing_end_month': 7, 'harvest_start_month': 9, 'harvest_end_month': 10, 'soil_suitability': 'Moderate', 'irrigation_suitability': 'Rainfed', 'regional_suitability': 'UNKNOWN', 'status': 'Active', 'reason': 'Insufficient regional trial data for heavy monsoon season', 'source_id': 'src_icar_iihr'},

    # Muskmelon
    {'crop_code': 'muskmelon', 'state_name': 'Uttar Pradesh', 'district_name': 'Ghaziabad', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Zaid / Summer', 'sowing_start_month': 2, 'sowing_end_month': 3, 'harvest_start_month': 5, 'harvest_end_month': 6, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well / Drip', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'Riverbed and sandy loam warm summer package', 'source_id': 'src_up_agri'},
    {'crop_code': 'muskmelon', 'state_name': 'Punjab', 'district_name': 'Ludhiana', 'agro_climatic_zone': 'Trans-Gangetic Plain Zone', 'season': 'Zaid / Summer', 'sowing_start_month': 2, 'sowing_end_month': 3, 'harvest_start_month': 5, 'harvest_end_month': 6, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well / Drip', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'PAU recommended summer cucurbit package', 'source_id': 'src_pau_ludhiana'},
    {'crop_code': 'muskmelon', 'state_name': 'Jammu & Kashmir', 'district_name': None, 'agro_climatic_zone': 'Western Himalayan Zone', 'season': 'Winter', 'sowing_start_month': 11, 'sowing_end_month': 12, 'harvest_start_month': 3, 'harvest_end_month': 4, 'soil_suitability': 'Low', 'irrigation_suitability': 'Unsuitable', 'regional_suitability': 'NOT_SUITABLE', 'status': 'Active', 'reason': 'Low soil temperature and frost damage', 'source_id': 'src_icar_iihr'},

    # Summer Moong
    {'crop_code': 'summer_moong', 'state_name': 'Uttar Pradesh', 'district_name': 'Ghaziabad', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Zaid / Summer', 'sowing_start_month': 3, 'sowing_end_month': 4, 'harvest_start_month': 5, 'harvest_end_month': 6, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'ICAR-IIPR recommended short-duration Zaid pulse window', 'source_id': 'src_icar_iipr'},
    {'crop_code': 'summer_moong', 'state_name': 'Punjab', 'district_name': 'Ludhiana', 'agro_climatic_zone': 'Trans-Gangetic Plain Zone', 'season': 'Zaid / Summer', 'sowing_start_month': 3, 'sowing_end_month': 4, 'harvest_start_month': 5, 'harvest_end_month': 6, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'PAU recommended summer moong after wheat harvest', 'source_id': 'src_pau_ludhiana'},

    # Summer Urad
    {'crop_code': 'summer_urad', 'state_name': 'Uttar Pradesh', 'district_name': 'Ghaziabad', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Zaid / Summer', 'sowing_start_month': 3, 'sowing_end_month': 4, 'harvest_start_month': 5, 'harvest_end_month': 6, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'ICAR-IIPR recommended short-duration summer pulse', 'source_id': 'src_icar_iipr'},

    # Wheat & Paddy
    {'crop_code': 'rabi_wheat', 'state_name': 'Uttar Pradesh', 'district_name': 'Ghaziabad', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Rabi', 'sowing_start_month': 11, 'sowing_end_month': 12, 'harvest_start_month': 3, 'harvest_end_month': 4, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well / Canal', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'Primary Rabi cereal staple across Gangetic plains', 'source_id': 'src_up_agri'},
    {'crop_code': 'paddy', 'state_name': 'Uttar Pradesh', 'district_name': 'Ghaziabad', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Kharif', 'sowing_start_month': 6, 'sowing_end_month': 7, 'harvest_start_month': 10, 'harvest_end_month': 11, 'soil_suitability': 'High', 'irrigation_suitability': 'Canal / Tube well', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'Primary Kharif cereal staple under canal irrigation', 'source_id': 'src_up_agri'},

    # Vegetables (Tomato, Potato, Mustard, Chana)
    {'crop_code': 'chana', 'state_name': 'Uttar Pradesh', 'district_name': 'Ghaziabad', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Rabi', 'sowing_start_month': 10, 'sowing_end_month': 11, 'harvest_start_month': 3, 'harvest_end_month': 4, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well / Rainfed', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'Rabi pulse staple', 'source_id': 'src_icar_iipr'},
    {'crop_code': 'mustard', 'state_name': 'Punjab', 'district_name': 'Ludhiana', 'agro_climatic_zone': 'Trans-Gangetic Plain Zone', 'season': 'Rabi', 'sowing_start_month': 10, 'sowing_end_month': 10, 'harvest_start_month': 2, 'harvest_end_month': 3, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'PAU recommended Rabi oilseed package', 'source_id': 'src_pau_ludhiana'},
    {'crop_code': 'tomato', 'state_name': 'Karnataka', 'district_name': 'Bengaluru Rural', 'agro_climatic_zone': 'Southern Plateau and Hills Zone', 'season': 'Kharif / Rabi', 'sowing_start_month': 8, 'sowing_end_month': 11, 'harvest_start_month': 11, 'harvest_end_month': 4, 'soil_suitability': 'High', 'irrigation_suitability': 'Drip / Tube well', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'ICAR-IIHR recommended commercial tomato zone', 'source_id': 'src_icar_iihr'},
    {'crop_code': 'potato', 'state_name': 'Uttar Pradesh', 'district_name': 'Agra', 'agro_climatic_zone': 'Upper Gangetic Plain Zone', 'season': 'Rabi', 'sowing_start_month': 10, 'sowing_end_month': 11, 'harvest_start_month': 1, 'harvest_end_month': 3, 'soil_suitability': 'High', 'irrigation_suitability': 'Tube well', 'regional_suitability': 'SUITABLE', 'status': 'Active', 'reason': 'Major UP potato belt package', 'source_id': 'src_up_agri'},
]

SEED_ECONOMIC_PROFILES = [
    {'crop_code': 'watermelon', 'yield_min_qtl_acre': 120.0, 'yield_typical_qtl_acre': 150.0, 'yield_max_qtl_acre': 180.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 3500.0, 'fertilizer_cost_per_acre': 4200.0, 'pesticide_cost_per_acre': 1800.0, 'labour_cost_per_acre': 6500.0, 'irrigation_cost_per_acre': 2000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 15000.0, 'total_cost_typical': 18000.0, 'total_cost_max': 22000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_up_agri'},
    {'crop_code': 'muskmelon', 'yield_min_qtl_acre': 80.0, 'yield_typical_qtl_acre': 100.0, 'yield_max_qtl_acre': 120.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 3200.0, 'fertilizer_cost_per_acre': 3800.0, 'pesticide_cost_per_acre': 1600.0, 'labour_cost_per_acre': 5800.0, 'irrigation_cost_per_acre': 1800.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 14000.0, 'total_cost_typical': 16200.0, 'total_cost_max': 19000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iihr'},
    {'crop_code': 'summer_moong', 'yield_min_qtl_acre': 3.5, 'yield_typical_qtl_acre': 4.5, 'yield_max_qtl_acre': 5.5, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1200.0, 'fertilizer_cost_per_acre': 1500.0, 'pesticide_cost_per_acre': 800.0, 'labour_cost_per_acre': 3000.0, 'irrigation_cost_per_acre': 1000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 6000.0, 'total_cost_typical': 7500.0, 'total_cost_max': 9000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iipr'},
    {'crop_code': 'summer_urad', 'yield_min_qtl_acre': 3.0, 'yield_typical_qtl_acre': 4.0, 'yield_max_qtl_acre': 5.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1150.0, 'fertilizer_cost_per_acre': 1450.0, 'pesticide_cost_per_acre': 750.0, 'labour_cost_per_acre': 2950.0, 'irrigation_cost_per_acre': 950.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 5800.0, 'total_cost_typical': 7250.0, 'total_cost_max': 8800.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iipr'},
    {'crop_code': 'cowpea', 'yield_min_qtl_acre': 4.0, 'yield_typical_qtl_acre': 5.0, 'yield_max_qtl_acre': 6.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1000.0, 'fertilizer_cost_per_acre': 1300.0, 'pesticide_cost_per_acre': 700.0, 'labour_cost_per_acre': 2700.0, 'irrigation_cost_per_acre': 800.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 5200.0, 'total_cost_typical': 6500.0, 'total_cost_max': 8000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iipr'},
    {'crop_code': 'summer_sesame', 'yield_min_qtl_acre': 2.5, 'yield_typical_qtl_acre': 3.0, 'yield_max_qtl_acre': 3.8, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 900.0, 'fertilizer_cost_per_acre': 1200.0, 'pesticide_cost_per_acre': 600.0, 'labour_cost_per_acre': 2500.0, 'irrigation_cost_per_acre': 800.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 4800.0, 'total_cost_typical': 6000.0, 'total_cost_max': 7500.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_tnau'},
    {'crop_code': 'fodder_maize', 'yield_min_qtl_acre': 100.0, 'yield_typical_qtl_acre': 120.0, 'yield_max_qtl_acre': 140.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1100.0, 'fertilizer_cost_per_acre': 1400.0, 'pesticide_cost_per_acre': 400.0, 'labour_cost_per_acre': 2000.0, 'irrigation_cost_per_acre': 600.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 4500.0, 'total_cost_typical': 5500.0, 'total_cost_max': 7000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iari'},
    {'crop_code': 'chana', 'yield_min_qtl_acre': 5.5, 'yield_typical_qtl_acre': 7.0, 'yield_max_qtl_acre': 8.5, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1600.0, 'fertilizer_cost_per_acre': 1800.0, 'pesticide_cost_per_acre': 900.0, 'labour_cost_per_acre': 3200.0, 'irrigation_cost_per_acre': 1000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 7000.0, 'total_cost_typical': 8500.0, 'total_cost_max': 10500.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iipr'},
    {'crop_code': 'arhar', 'yield_min_qtl_acre': 5.0, 'yield_typical_qtl_acre': 6.5, 'yield_max_qtl_acre': 8.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1400.0, 'fertilizer_cost_per_acre': 2000.0, 'pesticide_cost_per_acre': 1100.0, 'labour_cost_per_acre': 3500.0, 'irrigation_cost_per_acre': 1000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 7500.0, 'total_cost_typical': 9000.0, 'total_cost_max': 11500.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iipr'},
    {'crop_code': 'mustard', 'yield_min_qtl_acre': 6.0, 'yield_typical_qtl_acre': 8.0, 'yield_max_qtl_acre': 10.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1200.0, 'fertilizer_cost_per_acre': 2200.0, 'pesticide_cost_per_acre': 800.0, 'labour_cost_per_acre': 2800.0, 'irrigation_cost_per_acre': 1000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 6500.0, 'total_cost_typical': 8000.0, 'total_cost_max': 10000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_pau_ludhiana'},
    {'crop_code': 'maize', 'yield_min_qtl_acre': 14.0, 'yield_typical_qtl_acre': 18.0, 'yield_max_qtl_acre': 22.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 2200.0, 'fertilizer_cost_per_acre': 3000.0, 'pesticide_cost_per_acre': 1200.0, 'labour_cost_per_acre': 3600.0, 'irrigation_cost_per_acre': 1000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 9000.0, 'total_cost_typical': 11000.0, 'total_cost_max': 13500.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iari'},
    {'crop_code': 'rabi_wheat', 'yield_min_qtl_acre': 15.0, 'yield_typical_qtl_acre': 18.0, 'yield_max_qtl_acre': 22.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1800.0, 'fertilizer_cost_per_acre': 3200.0, 'pesticide_cost_per_acre': 1000.0, 'labour_cost_per_acre': 4500.0, 'irrigation_cost_per_acre': 2000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 10000.0, 'total_cost_typical': 12500.0, 'total_cost_max': 15000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_up_agri'},
    {'crop_code': 'paddy', 'yield_min_qtl_acre': 18.0, 'yield_typical_qtl_acre': 22.0, 'yield_max_qtl_acre': 26.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 1500.0, 'fertilizer_cost_per_acre': 3500.0, 'pesticide_cost_per_acre': 1500.0, 'labour_cost_per_acre': 5500.0, 'irrigation_cost_per_acre': 2000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 11500.0, 'total_cost_typical': 14000.0, 'total_cost_max': 17000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_up_agri'},
    {'crop_code': 'sugarcane', 'yield_min_qtl_acre': 280.0, 'yield_typical_qtl_acre': 320.0, 'yield_max_qtl_acre': 360.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 7000.0, 'fertilizer_cost_per_acre': 8500.0, 'pesticide_cost_per_acre': 2500.0, 'labour_cost_per_acre': 12000.0, 'irrigation_cost_per_acre': 5000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 28000.0, 'total_cost_typical': 35000.0, 'total_cost_max': 42000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_up_agri'},
    {'crop_code': 'tomato', 'yield_min_qtl_acre': 90.0, 'yield_typical_qtl_acre': 110.0, 'yield_max_qtl_acre': 130.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 4000.0, 'fertilizer_cost_per_acre': 5500.0, 'pesticide_cost_per_acre': 3500.0, 'labour_cost_per_acre': 7000.0, 'irrigation_cost_per_acre': 2000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 18000.0, 'total_cost_typical': 22000.0, 'total_cost_max': 27000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iihr'},
    {'crop_code': 'potato', 'yield_min_qtl_acre': 80.0, 'yield_typical_qtl_acre': 100.0, 'yield_max_qtl_acre': 120.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 8000.0, 'fertilizer_cost_per_acre': 5000.0, 'pesticide_cost_per_acre': 2500.0, 'labour_cost_per_acre': 6500.0, 'irrigation_cost_per_acre': 3000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 21000.0, 'total_cost_typical': 25000.0, 'total_cost_max': 30000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_up_agri'},
    {'crop_code': 'onion', 'yield_min_qtl_acre': 75.0, 'yield_typical_qtl_acre': 90.0, 'yield_max_qtl_acre': 110.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 3500.0, 'fertilizer_cost_per_acre': 4800.0, 'pesticide_cost_per_acre': 2200.0, 'labour_cost_per_acre': 6500.0, 'irrigation_cost_per_acre': 3000.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 16500.0, 'total_cost_typical': 20000.0, 'total_cost_max': 25000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iihr'},
    {'crop_code': 'okra', 'yield_min_qtl_acre': 35.0, 'yield_typical_qtl_acre': 45.0, 'yield_max_qtl_acre': 55.0, 'yield_unit': 'qtl/acre', 'seed_cost_per_acre': 2200.0, 'fertilizer_cost_per_acre': 3000.0, 'pesticide_cost_per_acre': 1800.0, 'labour_cost_per_acre': 3500.0, 'irrigation_cost_per_acre': 1500.0, 'machinery_cost_per_acre': None, 'other_cost_per_acre': None, 'total_cost_min': 10000.0, 'total_cost_typical': 12000.0, 'total_cost_max': 15000.0, 'cost_period': 'Per Crop Season', 'currency': 'INR', 'source_id': 'src_icar_iihr'},
]

SEED_REGIONAL_CALENDAR = [{'active': True,
  'agro_climatic_zone': 'Upper Gangetic Plain Zone',
  'confidence_weight': 0.95,
  'crop_name': 'Summer Moong',
  'district_name': 'Ghaziabad',
  'harvest_end_month': 7,
  'harvest_start_month': 5,
  'irrigation_condition': 'Tube well',
  'regional_suitability': 'High',
  'source': 'ICAR-IIPR Kanpur / UP Agri Dept Guidelines',
  'source_id': 'src_icar_iipr',
  'source_scope': 'DISTRICT',
  'sowing_end_month': 5,
  'sowing_start_month': 3,
  'state_name': 'Uttar Pradesh',
  'verification_status': 'VERIFIED'},
 {'active': True,
  'agro_climatic_zone': 'Upper Gangetic Plain Zone',
  'confidence_weight': 0.9,
  'crop_name': 'Summer Urad',
  'district_name': 'Ghaziabad',
  'harvest_end_month': 6,
  'harvest_start_month': 5,
  'irrigation_condition': 'Tube well',
  'regional_suitability': 'High',
  'source': 'UP State Agri Dept Zaid Guidelines',
  'source_id': 'src_up_agri',
  'source_scope': 'DISTRICT',
  'sowing_end_month': 4,
  'sowing_start_month': 3,
  'state_name': 'Uttar Pradesh',
  'verification_status': 'VERIFIED'},
 {'active': True,
  'agro_climatic_zone': 'Trans-Gangetic Plain Zone',
  'confidence_weight': 0.98,
  'crop_name': 'Summer Moong',
  'district_name': 'Ludhiana',
  'harvest_end_month': 6,
  'harvest_start_month': 5,
  'irrigation_condition': 'Tube well',
  'regional_suitability': 'High',
  'source': 'Punjab Agricultural University (PAU), Ludhiana Farm Advisory',
  'source_id': 'src_pau_ludhiana',
  'source_scope': 'DISTRICT',
  'sowing_end_month': 4,
  'sowing_start_month': 3,
  'state_name': 'Punjab',
  'verification_status': 'VERIFIED'},
 {'active': True,
  'agro_climatic_zone': 'Trans-Gangetic Plain Zone',
  'confidence_weight': 0.9,
  'crop_name': 'Fodder Maize',
  'district_name': 'Ludhiana',
  'harvest_end_month': 7,
  'harvest_start_month': 5,
  'irrigation_condition': 'Canal',
  'regional_suitability': 'High',
  'source': 'PAU Ludhiana Package of Practices',
  'source_id': 'src_pau_ludhiana',
  'source_scope': 'DISTRICT',
  'sowing_end_month': 5,
  'sowing_start_month': 3,
  'state_name': 'Punjab',
  'verification_status': 'VERIFIED'},
 {'active': True,
  'agro_climatic_zone': 'East Coast Plains and Hills Zone',
  'confidence_weight': 0.95,
  'crop_name': 'Cowpea (Lobia)',
  'district_name': 'Thanjavur',
  'harvest_end_month': 5,
  'harvest_start_month': 3,
  'irrigation_condition': 'Canal',
  'regional_suitability': 'High',
  'source': 'TNAU Agritech Rice Fallow Pulses Protocol',
  'source_id': 'src_tnau',
  'source_scope': 'DISTRICT',
  'sowing_end_month': 3,
  'sowing_start_month': 1,
  'state_name': 'Tamil Nadu',
  'verification_status': 'VERIFIED'},
 {'active': True,
  'agro_climatic_zone': 'Trans-Gangetic Plain Zone',
  'confidence_weight': 0.85,
  'crop_name': 'Summer Moong',
  'district_name': None,
  'harvest_end_month': 6,
  'harvest_start_month': 5,
  'irrigation_condition': 'All',
  'regional_suitability': 'High',
  'source': 'Trans-Gangetic Plain ICAR Regional Agronomy Guide',
  'source_id': 'src_icar_iipr',
  'source_scope': 'AGRO_CLIMATIC_ZONE',
  'sowing_end_month': 4,
  'sowing_start_month': 3,
  'state_name': 'Haryana',
  'verification_status': 'VERIFIED'}]

SEED_NUTRIENT_PROFILES = [{'crop_name': 'Wheat',
  'is_legume': False,
  'nitrogen_effect': 'Relatively high nitrogen extraction from cereal harvest',
  'organic_matter_effect': 'Low residual organic matter if stubble is removed',
  'phosphorus_effect': 'Moderate phosphorus removal',
  'potassium_effect': 'Moderate potassium removal',
  'rotation_notes': 'Wheat leaves soil in need of nitrogen replenishment; ideal candidate for legume rotation.',
  'source': 'ICAR Agronomy Handbook',
  'verification_status': 'VERIFIED'},
 {'crop_name': 'Mustard',
  'is_legume': False,
  'nitrogen_effect': 'Moderate nitrogen removal',
  'organic_matter_effect': 'Root biomass adds minor organic matter',
  'phosphorus_effect': 'High phosphorus & sulphur uptake',
  'potassium_effect': 'Moderate potassium removal',
  'rotation_notes': 'Mustard consumes soil sulphur; short pulse rotation helps rebuild soil structure.',
  'source': 'ICAR-DRMR Bharatpur Baseline Guide',
  'verification_status': 'VERIFIED'},
 {'crop_name': 'Potato',
  'is_legume': False,
  'nitrogen_effect': 'High nutrient removal, moderate residual N from fertilizer application',
  'organic_matter_effect': 'Favorable soil tilth remaining after harvest',
  'phosphorus_effect': 'High residual phosphorus in topsoil',
  'potassium_effect': 'Heavy potassium depletion',
  'rotation_notes': 'Heavy feeder crop; short legume gap crop utilizes residual P and restores N.',
  'source': 'ICAR-CPRI Shimla Technical Bulletin',
  'verification_status': 'VERIFIED'}]

SEED_COMPATIBILITY_MATRIX = [{'candidate_crop': 'Summer Moong',
  'compatibility_status': 'Compatible',
  'previous_crop': 'Wheat',
  'rotation_notes': 'Excellent cereal-legume rotation. Moong fixes atmospheric nitrogen for subsequent Kharif paddy.',
  'source': 'ICAR Agronomy Guidelines',
  'verification_status': 'VERIFIED'},
 {'candidate_crop': 'Summer Urad',
  'compatibility_status': 'Compatible',
  'previous_crop': 'Wheat',
  'rotation_notes': 'Favorable cereal-legume sequence with good soil health restoration.',
  'source': 'ICAR Agronomy Guidelines',
  'verification_status': 'VERIFIED'},
 {'candidate_crop': 'Cowpea (Lobia)',
  'compatibility_status': 'Compatible',
  'previous_crop': 'Wheat',
  'rotation_notes': 'Short duration legume ideal after wheat harvest.',
  'source': 'ICAR Agronomy Guidelines',
  'verification_status': 'VERIFIED'},
 {'candidate_crop': 'Summer Sesame (Til)',
  'compatibility_status': 'Compatible',
  'previous_crop': 'Wheat',
  'rotation_notes': 'Suitable non-legume cash crop after wheat if gap window is 75+ days.',
  'source': 'ICAR Agronomy Guidelines',
  'verification_status': 'VERIFIED'},
 {'candidate_crop': 'Fodder Maize',
  'compatibility_status': 'Caution',
  'previous_crop': 'Wheat',
  'rotation_notes': 'Cereal after cereal requires additional nitrogen management.',
  'source': 'ICAR Agronomy Guidelines',
  'verification_status': 'VERIFIED'}]

SEED_DISTRICT_ZONE_MAP = {('Andaman and Nicobar Islands', 'Port Blair'): 'The Islands Zone',
 ('Andhra Pradesh', 'Guntur'): 'East Coast Plains and Hills Zone',
 ('Andhra Pradesh', 'Krishna'): 'East Coast Plains and Hills Zone',
 ('Arunachal Pradesh', 'Itanagar'): 'Eastern Himalayan Region',
 ('Assam', 'Guwahati'): 'Eastern Himalayan Region',
 ('Bihar', 'Gaya'): 'Middle Gangetic Plain Zone',
 ('Bihar', 'Muzaffarpur'): 'Middle Gangetic Plain Zone',
 ('Bihar', 'Patna'): 'Middle Gangetic Plain Zone',
 ('Chandigarh', 'Chandigarh'): 'Trans-Gangetic Plain Zone',
 ('Chhattisgarh', 'Raipur'): 'Eastern Plateau and Hills Zone',
 ('Dadra and Nagar Haveli and Daman and Diu', 'Daman'): 'West Coast Plains and Ghats Zone',
 ('Delhi', 'New Delhi'): 'Trans-Gangetic Plain Zone',
 ('Goa', 'North Goa'): 'West Coast Plains and Ghats Zone',
 ('Gujarat', 'Ahmedabad'): 'Gujarat Plains and Hills Zone',
 ('Gujarat', 'Rajkot'): 'Gujarat Plains and Hills Zone',
 ('Gujarat', 'Surat'): 'Gujarat Plains and Hills Zone',
 ('Haryana', 'Ambala'): 'Trans-Gangetic Plain Zone',
 ('Haryana', 'Hisar'): 'Trans-Gangetic Plain Zone',
 ('Haryana', 'Karnal'): 'Trans-Gangetic Plain Zone',
 ('Haryana', 'Rohtak'): 'Trans-Gangetic Plain Zone',
 ('Himachal Pradesh', 'Shimla'): 'Western Himalayan Region',
 ('Jammu and Kashmir', 'Jammu'): 'Western Himalayan Region',
 ('Jammu and Kashmir', 'Srinagar'): 'Western Himalayan Region',
 ('Jharkhand', 'Ranchi'): 'Eastern Plateau and Hills Zone',
 ('Karnataka', 'Bengaluru'): 'Southern Plateau and Hills Zone',
 ('Karnataka', 'Mysuru'): 'Southern Plateau and Hills Zone',
 ('Kerala', 'Idukki'): 'West Coast Plains and Ghats Zone',
 ('Kerala', 'Palakkad'): 'West Coast Plains and Ghats Zone',
 ('Kerala', 'Wayanad'): 'West Coast Plains and Ghats Zone',
 ('Ladakh', 'Leh'): 'Western Himalayan Region',
 ('Lakshadweep', 'Kavaratti'): 'The Islands Zone',
 ('Madhya Pradesh', 'Bhopal'): 'Central Plateau and Hills Zone',
 ('Madhya Pradesh', 'Gwalior'): 'Central Plateau and Hills Zone',
 ('Madhya Pradesh', 'Indore'): 'Western Plateau and Hills Zone',
 ('Maharashtra', 'Nagpur'): 'Western Plateau and Hills Zone',
 ('Maharashtra', 'Nashik'): 'Western Plateau and Hills Zone',
 ('Maharashtra', 'Pune'): 'Western Plateau and Hills Zone',
 ('Manipur', 'Imphal'): 'Eastern Himalayan Region',
 ('Meghalaya', 'Shillong'): 'Eastern Himalayan Region',
 ('Mizoram', 'Aizawl'): 'Eastern Himalayan Region',
 ('Nagaland', 'Kohima'): 'Eastern Himalayan Region',
 ('Odisha', 'Puri'): 'East Coast Plains and Hills Zone',
 ('Puducherry', 'Puducherry'): 'East Coast Plains and Hills Zone',
 ('Punjab', 'Amritsar'): 'Trans-Gangetic Plain Zone',
 ('Punjab', 'Bhatinda'): 'Trans-Gangetic Plain Zone',
 ('Punjab', 'Jalandhar'): 'Trans-Gangetic Plain Zone',
 ('Punjab', 'Ludhiana'): 'Trans-Gangetic Plain Zone',
 ('Punjab', 'Patiala'): 'Trans-Gangetic Plain Zone',
 ('Rajasthan', 'Bikaner'): 'Western Dry Region',
 ('Rajasthan', 'Jaipur'): 'Central Plateau and Hills Zone',
 ('Rajasthan', 'Jaisalmer'): 'Western Dry Region',
 ('Rajasthan', 'Jodhpur'): 'Western Dry Region',
 ('Rajasthan', 'Udaipur'): 'Central Plateau and Hills Zone',
 ('Sikkim', 'Gangtok'): 'Eastern Himalayan Region',
 ('Tamil Nadu', 'Chennai'): 'East Coast Plains and Hills Zone',
 ('Tamil Nadu', 'Coimbatore'): 'Southern Plateau and Hills Zone',
 ('Tamil Nadu', 'Cuddalore'): 'East Coast Plains and Hills Zone',
 ('Tamil Nadu', 'Madurai'): 'Southern Plateau and Hills Zone',
 ('Tamil Nadu', 'Salem'): 'Southern Plateau and Hills Zone',
 ('Tamil Nadu', 'Thanjavur'): 'East Coast Plains and Hills Zone',
 ('Tamil Nadu', 'Trichy'): 'Southern Plateau and Hills Zone',
 ('Telangana', 'Hyderabad'): 'Southern Plateau and Hills Zone',
 ('Telangana', 'Warangal'): 'Southern Plateau and Hills Zone',
 ('Tripura', 'Agartala'): 'Eastern Himalayan Region',
 ('Uttar Pradesh', 'Agra'): 'Upper Gangetic Plain Zone',
 ('Uttar Pradesh', 'Ghaziabad'): 'Upper Gangetic Plain Zone',
 ('Uttar Pradesh', 'Gorakhpur'): 'Middle Gangetic Plain Zone',
 ('Uttar Pradesh', 'Kanpur'): 'Upper Gangetic Plain Zone',
 ('Uttar Pradesh', 'Lucknow'): 'Upper Gangetic Plain Zone',
 ('Uttar Pradesh', 'Meerut'): 'Upper Gangetic Plain Zone',
 ('Uttar Pradesh', 'Varanasi'): 'Middle Gangetic Plain Zone',
 ('Uttarakhand', 'Dehradun'): 'Western Himalayan Region',
 ('West Bengal', 'Burdwan'): 'Lower Gangetic Plain Zone',
 ('West Bengal', 'Kolkata'): 'Lower Gangetic Plain Zone'}

# Legacy aliases for Phase 1 service backwards compatibility
SEED_CROP_PROFILES = SEED_CROP_CATALOG
SEED_CROP_COMPATIBILITY = SEED_COMPATIBILITY_MATRIX

def seed_knowledge_base(db: Session) -> Dict[str, int]:
    # Idempotently seeds authoritative Phase 3A.2 Crop Knowledge Base records.
    from app.modules.gap_crop.models import (
        AgriculturalSourceModel,
        CropAgronomicProfile,
        CropEconomicProfile,
        CropMaster,
        CropRegionalProfile,
    )

    stats = {
        'sources': 0,
        'crops': 0,
        'agronomic_profiles': 0,
        'regional_profiles': 0,
        'economic_profiles': 0,
    }

    # 1. Seed Agricultural Sources
    sources_map = {}
    for s_data in SEED_SOURCES:
        existing = db.query(AgriculturalSourceModel).filter_by(organization=s_data['organization'], source_title=s_data['source_title']).first()
        if not existing:
            existing = AgriculturalSourceModel(
                tier=s_data['tier'],
                organization=s_data['organization'],
                source_title=s_data['source_title'],
                url=s_data.get('url'),
                document_identifier=s_data.get('document_identifier'),
                publication_year=s_data.get('publication_year'),
                verification_status=s_data.get('verification_status', 'VERIFIED'),
                source_type=s_data.get('source_type'),
                notes=s_data.get('notes'),
            )
            db.add(existing)
            db.flush()
            stats['sources'] += 1
        sources_map[s_data['id']] = existing.id

    # 2. Seed Master Crops
    crop_map = {}
    for c_data in SEED_CROP_CATALOG:
        existing = db.query(CropMaster).filter_by(code=c_data['code']).first()
        if not existing:
            existing = CropMaster(
                crop_name=c_data['crop_name'],
                code=c_data['code'],
                scientific_name=c_data.get('scientific_name'),
                hindi_name=c_data['hindi_name'],
                category=c_data['category'],
                sub_category=c_data.get('sub_category'),
                growth_habit=c_data.get('growth_habit', 'Annual'),
                is_gap_candidate=c_data.get('is_gap_candidate', True),
                min_duration_days=c_data['min_duration_days'],
                max_duration_days=c_data['max_duration_days'],
                water_requirement=c_data['water_requirement'],
                season=c_data['season'],
                is_legume=c_data['is_legume'],
                expected_yield_qtl_per_acre=c_data.get('expected_yield_qtl_per_acre', 4.5),
                net_profit_per_acre_min=c_data.get('net_profit_per_acre_min', 20000),
                net_profit_per_acre_max=c_data.get('net_profit_per_acre_max', 30000),
                investment_per_acre=c_data.get('investment_per_acre', 7500),
                market_price_per_quintal=c_data.get('market_price_per_quintal', 6950),
                description=c_data.get('description'),
            )
            db.add(existing)
            db.flush()
            stats['crops'] += 1
        crop_map[c_data['code']] = existing.id

    # 3. Seed Agronomic Profiles
    for a_data in SEED_AGRONOMIC_PROFILES:
        c_id = crop_map.get(a_data['crop_code'])
        if c_id:
            existing = db.query(CropAgronomicProfile).filter_by(crop_id=c_id).first()
            if not existing:
                s_id = sources_map.get(a_data.get('source_id'))
                ag_prof = CropAgronomicProfile(
                    crop_id=c_id,
                    temperature_min_c=a_data.get('temperature_min_c'),
                    temperature_optimal_min_c=a_data.get('temperature_optimal_min_c'),
                    temperature_optimal_max_c=a_data.get('temperature_optimal_max_c'),
                    temperature_max_c=a_data.get('temperature_max_c'),
                    rainfall_min_mm=a_data.get('rainfall_min_mm'),
                    rainfall_optimal_min_mm=a_data.get('rainfall_optimal_min_mm'),
                    rainfall_optimal_max_mm=a_data.get('rainfall_optimal_max_mm'),
                    soil_types=a_data.get('soil_types'),
                    soil_ph_min=a_data.get('soil_ph_min'),
                    soil_ph_max=a_data.get('soil_ph_max'),
                    water_requirement=a_data.get('water_requirement'),
                    irrigation_requirement=a_data.get('irrigation_requirement'),
                    waterlogging_tolerance=a_data.get('waterlogging_tolerance'),
                    drought_tolerance=a_data.get('drought_tolerance'),
                    heat_sensitivity=a_data.get('heat_sensitivity'),
                    sowing_window=a_data.get('sowing_window'),
                    harvest_window=a_data.get('harvest_window'),
                    source_id=s_id,
                )
                db.add(ag_prof)
                stats['agronomic_profiles'] += 1

    # 4. Seed Regional Profiles
    for r_data in SEED_REGIONAL_PROFILES:
        c_id = crop_map.get(r_data['crop_code'])
        if c_id:
            existing = db.query(CropRegionalProfile).filter_by(
                crop_id=c_id, state_name=r_data['state_name'], season=r_data['season']
            ).first()
            if not existing:
                s_id = sources_map.get(r_data.get('source_id'))
                reg_prof = CropRegionalProfile(
                    crop_id=c_id,
                    state_name=r_data['state_name'],
                    district_name=r_data.get('district_name'),
                    agro_climatic_zone=r_data.get('agro_climatic_zone'),
                    season=r_data['season'],
                    sowing_start_month=r_data.get('sowing_start_month'),
                    sowing_end_month=r_data.get('sowing_end_month'),
                    harvest_start_month=r_data.get('harvest_start_month'),
                    harvest_end_month=r_data.get('harvest_end_month'),
                    soil_suitability=r_data.get('soil_suitability'),
                    irrigation_suitability=r_data.get('irrigation_suitability'),
                    regional_suitability=r_data.get('regional_suitability', 'SUITABLE'),
                    status=r_data.get('status', 'Active'),
                    reason=r_data.get('reason'),
                    source_id=s_id,
                )
                db.add(reg_prof)
                stats['regional_profiles'] += 1

    # 5. Seed Economic Profiles
    for e_data in SEED_ECONOMIC_PROFILES:
        c_id = crop_map.get(e_data['crop_code'])
        if c_id:
            existing = db.query(CropEconomicProfile).filter_by(crop_id=c_id).first()
            if not existing:
                s_id = sources_map.get(e_data.get('source_id'))
                econ_prof = CropEconomicProfile(
                    crop_id=c_id,
                    yield_min_qtl_acre=e_data.get('yield_min_qtl_acre'),
                    yield_typical_qtl_acre=e_data.get('yield_typical_qtl_acre'),
                    yield_max_qtl_acre=e_data.get('yield_max_qtl_acre'),
                    yield_unit=e_data.get('yield_unit', 'qtl/acre'),
                    seed_cost_per_acre=e_data.get('seed_cost_per_acre'),
                    fertilizer_cost_per_acre=e_data.get('fertilizer_cost_per_acre'),
                    pesticide_cost_per_acre=e_data.get('pesticide_cost_per_acre'),
                    labour_cost_per_acre=e_data.get('labour_cost_per_acre'),
                    irrigation_cost_per_acre=e_data.get('irrigation_cost_per_acre'),
                    machinery_cost_per_acre=e_data.get('machinery_cost_per_acre'),
                    other_cost_per_acre=e_data.get('other_cost_per_acre'),
                    total_cost_min=e_data.get('total_cost_min'),
                    total_cost_typical=e_data.get('total_cost_typical'),
                    total_cost_max=e_data.get('total_cost_max'),
                    cost_period=e_data.get('cost_period', 'Per Crop Season'),
                    currency=e_data.get('currency', 'INR'),
                    source_id=s_id,
                )
                db.add(econ_prof)
                stats['economic_profiles'] += 1

    db.commit()
    return stats
