"""Seed data for Gap Crop Recommendation Engine.

Data honesty rules (Phase 1 §24):
- Explicit provenance for all records.
- Seed/demo data marked as 'Demo/seed data — requires source verification' where unverified.
- Scientifically cautious wording.
"""

from __future__ import annotations

# Controlled initial crop catalog (Minimum 5 crops)
SEED_CROP_CATALOG = [
    {
        "code": "summer_moong",
        "crop_name": "Summer Moong",
        "scientific_name": "Vigna radiata",
        "hindi_name": "ग्रीष्मकालीन मूंग",
        "category": "Pulse",
        "min_duration_days": 60,
        "max_duration_days": 65,
        "water_requirement": "Low",
        "season": "Zaid / Summer",
        "is_legume": True,
        "expected_yield_qtl_per_acre": 4.5,
        "net_profit_per_acre_min": 22000,
        "net_profit_per_acre_max": 30000,
        "investment_per_acre": 7500,
        "market_price_per_quintal": 6950,
        "description": "Ideal 60-65 day short duration pulse after Wheat harvest. Fixes atmospheric Nitrogen and yields high market value.",
        "active": True,
    },
    {
        "code": "urad",
        "crop_name": "Summer Urad",
        "scientific_name": "Vigna mungo",
        "hindi_name": "ग्रीष्मकालीन उड़द",
        "category": "Pulse",
        "min_duration_days": 65,
        "max_duration_days": 70,
        "water_requirement": "Medium",
        "season": "Zaid / Summer",
        "is_legume": True,
        "expected_yield_qtl_per_acre": 4.0,
        "net_profit_per_acre_min": 18000,
        "net_profit_per_acre_max": 25000,
        "investment_per_acre": 8000,
        "market_price_per_quintal": 6820,
        "description": "High value pulse crop, restores soil nitrogen and organic matter between cereal rotations.",
        "active": True,
    },
    {
        "code": "cowpea",
        "crop_name": "Cowpea (Lobia)",
        "scientific_name": "Vigna unguiculata",
        "hindi_name": "लोबिया / बरबटी",
        "category": "Pulse",
        "min_duration_days": 50,
        "max_duration_days": 60,
        "water_requirement": "Low",
        "season": "Zaid / Summer",
        "is_legume": True,
        "expected_yield_qtl_per_acre": 6.0,
        "net_profit_per_acre_min": 15000,
        "net_profit_per_acre_max": 22000,
        "investment_per_acre": 6500,
        "market_price_per_quintal": 4500,
        "description": "Ultra-short duration leguminous gap crop. Rapid biomass generation and excellent drought tolerance.",
        "active": True,
    },
    {
        "code": "sesame",
        "crop_name": "Summer Sesame (Til)",
        "scientific_name": "Sesamum indicum",
        "hindi_name": "ग्रीष्मकालीन तिल",
        "category": "Oilseed",
        "min_duration_days": 75,
        "max_duration_days": 85,
        "water_requirement": "Low",
        "season": "Zaid / Summer",
        "is_legume": False,
        "expected_yield_qtl_per_acre": 3.2,
        "net_profit_per_acre_min": 20000,
        "net_profit_per_acre_max": 28000,
        "investment_per_acre": 6000,
        "market_price_per_quintal": 9500,
        "description": "High value oilseed with low irrigation requirement. Requires 75+ day gap window.",
        "active": True,
    },
    {
        "code": "fodder_maize",
        "crop_name": "Fodder Maize",
        "scientific_name": "Zea mays",
        "hindi_name": "हरा चारे का मक्का",
        "category": "Fodder",
        "min_duration_days": 45,
        "max_duration_days": 55,
        "water_requirement": "Medium",
        "season": "Zaid / Summer",
        "is_legume": False,
        "expected_yield_qtl_per_acre": 120.0,
        "net_profit_per_acre_min": 12000,
        "net_profit_per_acre_max": 18000,
        "investment_per_acre": 5000,
        "market_price_per_quintal": 250,
        "description": "Fast-growing green fodder crop for livestock. Fits narrow 45-55 day gap windows.",
        "active": True,
    },
]

# Regional Crop Calendar Seed Data
SEED_REGIONAL_CALENDAR = [
    {
        "state_name": "Uttar Pradesh",
        "district_name": "Ghaziabad",
        "crop_name": "Summer Moong",
        "sowing_start_month": 3,
        "sowing_end_month": 5,
        "harvest_start_month": 5,
        "harvest_end_month": 7,
        "regional_suitability": "High",
        "confidence_weight": 0.90,
        "source": "ICAR-IIPR Kanpur Zaid Advisory / Demo seed data — requires source verification",
        "active": True,
    },
    {
        "state_name": "Uttar Pradesh",
        "district_name": "Ghaziabad",
        "crop_name": "Summer Urad",
        "sowing_start_month": 3,
        "sowing_end_month": 4,
        "harvest_start_month": 5,
        "harvest_end_month": 6,
        "regional_suitability": "High",
        "confidence_weight": 0.85,
        "source": "UP State Agri Dept Zaid Guidelines / Demo seed data — requires source verification",
        "active": True,
    },
    {
        "state_name": "Uttar Pradesh",
        "district_name": "Ghaziabad",
        "crop_name": "Cowpea (Lobia)",
        "sowing_start_month": 3,
        "sowing_end_month": 5,
        "harvest_start_month": 5,
        "harvest_end_month": 7,
        "regional_suitability": "High",
        "confidence_weight": 0.85,
        "source": "ICAR-IIPR / Demo seed data — requires source verification",
        "active": True,
    },
    {
        "state_name": "Uttar Pradesh",
        "district_name": "Ghaziabad",
        "crop_name": "Summer Sesame (Til)",
        "sowing_start_month": 2,
        "sowing_end_month": 4,
        "harvest_start_month": 5,
        "harvest_end_month": 6,
        "regional_suitability": "Medium",
        "confidence_weight": 0.80,
        "source": "UP Agri Package of Practices / Demo seed data — requires source verification",
        "active": True,
    },
    {
        "state_name": "Uttar Pradesh",
        "district_name": "Ghaziabad",
        "crop_name": "Fodder Maize",
        "sowing_start_month": 3,
        "sowing_end_month": 6,
        "harvest_start_month": 5,
        "harvest_end_month": 7,
        "regional_suitability": "High",
        "confidence_weight": 0.90,
        "source": "ICAR-IGFRI Fodder Guidelines / Demo seed data — requires source verification",
        "active": True,
    },
]

# Crop Nutrient Profiles (Estimated impact, NOT a soil test)
SEED_NUTRIENT_PROFILES = [
    {
        "crop_name": "Wheat",
        "nitrogen_effect": "Relatively high nitrogen extraction from cereal harvest",
        "phosphorus_effect": "Moderate phosphorus removal",
        "potassium_effect": "Moderate potassium removal",
        "organic_matter_effect": "Low residual organic matter if stubble is removed",
        "is_legume": False,
        "rotation_notes": "Wheat leaves soil in need of nitrogen replenishment; ideal candidate for legume rotation.",
        "source": "ICAR Agronomy Handbook / Demo seed data — requires source verification",
    },
    {
        "crop_name": "Mustard",
        "nitrogen_effect": "Moderate nitrogen removal",
        "phosphorus_effect": "High phosphorus & sulphur uptake",
        "potassium_effect": "Moderate potassium removal",
        "organic_matter_effect": "Root biomass adds minor organic matter",
        "is_legume": False,
        "rotation_notes": "Mustard consumes soil sulphur; short pulse rotation helps rebuild soil structure.",
        "source": "ICAR-DRMR Bharatpur / Demo seed data — requires source verification",
    },
    {
        "crop_name": "Potato",
        "nitrogen_effect": "High nutrient removal, moderate residual N from high fertilizer application",
        "phosphorus_effect": "High residual phosphorus in topsoil",
        "potassium_effect": "Heavy potassium depletion",
        "organic_matter_effect": "Favorable soil tilth remaining after harvest",
        "is_legume": False,
        "rotation_notes": "Heavy feeder crop; short legume gap crop utilizes residual P and restores N.",
        "source": "ICAR-CPRI Shimla / Demo seed data — requires source verification",
    },
    {
        "crop_name": "Paddy",
        "nitrogen_effect": "Anaerobic N losses during flooding",
        "phosphorus_effect": "Moderate P availability under puddled soil",
        "potassium_effect": "High potassium uptake",
        "organic_matter_effect": "Compacted soil structure requiring aeration",
        "is_legume": False,
        "rotation_notes": "Continuous cereal rotation increases disease pressure; pulse gap crop breaks weed and pest cycles.",
        "source": "ICAR-NRRI Cuttack / Demo seed data — requires source verification",
    },
]

# Crop Compatibility Matrix
SEED_COMPATIBILITY_MATRIX = [
    # Wheat
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Summer Moong",
        "compatibility_status": "Compatible",
        "rotation_notes": "Excellent cereal-legume rotation. Moong fixes atmospheric nitrogen for subsequent Kharif paddy.",
        "source": "ICAR Agronomy Guidelines / Demo seed data — requires source verification",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Summer Urad",
        "compatibility_status": "Compatible",
        "rotation_notes": "Favorable cereal-legume sequence with good soil health restoration.",
        "source": "ICAR Agronomy Guidelines / Demo seed data — requires source verification",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Cowpea (Lobia)",
        "compatibility_status": "Compatible",
        "rotation_notes": "Short duration legume ideal after wheat harvest.",
        "source": "ICAR Agronomy Guidelines / Demo seed data — requires source verification",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Summer Sesame (Til)",
        "compatibility_status": "Compatible",
        "rotation_notes": "Suitable non-legume cash crop after wheat if gap window is 75+ days.",
        "source": "ICAR Agronomy Guidelines / Demo seed data — requires source verification",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Fodder Maize",
        "compatibility_status": "Caution",
        "rotation_notes": "Cereal after cereal requires additional nitrogen management.",
        "source": "ICAR Agronomy Guidelines / Demo seed data — requires source verification",
    },
    # Mustard
    {
        "previous_crop": "Mustard",
        "candidate_crop": "Summer Moong",
        "compatibility_status": "Compatible",
        "rotation_notes": "Oilseed to pulse transition breaks pest cycles and restores nitrogen.",
        "source": "ICAR-DRMR / Demo seed data — requires source verification",
    },
    {
        "previous_crop": "Mustard",
        "candidate_crop": "Cowpea (Lobia)",
        "compatibility_status": "Compatible",
        "rotation_notes": "Fast growing pulse restores organic carbon.",
        "source": "ICAR-DRMR / Demo seed data — requires source verification",
    },
    # Potato
    {
        "previous_crop": "Potato",
        "candidate_crop": "Summer Moong",
        "compatibility_status": "Compatible",
        "rotation_notes": "Moong utilizes residual fertilizers left from potato cultivation.",
        "source": "ICAR-CPRI / Demo seed data — requires source verification",
    },
    {
        "previous_crop": "Potato",
        "candidate_crop": "Cowpea (Lobia)",
        "compatibility_status": "Compatible",
        "rotation_notes": "Excellent short gap crop following early tuber harvest.",
        "source": "ICAR-CPRI / Demo seed data — requires source verification",
    },
]
