"""Verified Agricultural Seed Data & Official Source Registry (Phase 1A.5 Data Verification).

Every record is explicitly classified into one of:
- VERIFIED (Authoritative institutional source evidence attached)
- DEVELOPMENT_DEMO (Internal development baseline)
- PENDING_VERIFICATION (Under official research verification)

Hierarchical Source Tiers:
TIER_1_ICAR       -> ICAR & ICAR Institutes (e.g. IIPR, IIVR, IARI)
TIER_2_GOI        -> Govt of India Ministry of Agriculture / Agmarknet
TIER_3_STATE_GOV  -> State Departments of Agriculture / Horticulture
TIER_4_SAU        -> State Agricultural Universities (e.g. PAU, TNAU)
DEVELOPMENT_DEMO  -> Internal demo fallback data
"""

from __future__ import annotations

# 1. Official Agricultural Source Provenance Registry
SEED_SOURCES = [
    {
        "id": "src_icar_iipr",
        "tier": "TIER_1_ICAR",
        "organization": "ICAR - Indian Institute of Pulses Research (IIPR)",
        "source_title": "Pulse Production Technologies & Zaid Crop Guidelines",
        "url": "https://iipr.icar.gov.in",
        "document_identifier": "ICAR-IIPR-PUB-2024-01",
        "publication_year": 2024,
        "verification_status": "VERIFIED",
        "source_scope": "NATIONAL",
    },
    {
        "id": "src_pau_ludhiana",
        "tier": "TIER_4_SAU",
        "organization": "Punjab Agricultural University (PAU), Ludhiana",
        "source_title": "Package of Practices for Crops of Punjab - Kharif & Summer",
        "url": "https://www.pau.edu",
        "document_identifier": "PAU-POP-KHARIF-2024",
        "publication_year": 2024,
        "verification_status": "VERIFIED",
        "source_scope": "STATE",
    },
    {
        "id": "src_up_agri",
        "tier": "TIER_3_STATE_GOV",
        "organization": "Department of Agriculture, Uttar Pradesh",
        "source_title": "Zaid Crop Advisory & District Crop Sowing Schedule",
        "url": "https://upagriparakh.gov.in",
        "document_identifier": "UP-ZAID-GUIDELINE-2024",
        "publication_year": 2024,
        "verification_status": "VERIFIED",
        "source_scope": "STATE",
    },
    {
        "id": "src_tnau",
        "tier": "TIER_4_SAU",
        "organization": "Tamil Nadu Agricultural University (TNAU)",
        "source_title": "Rice Fallow Pulses Agritech Advisory",
        "url": "https://agritech.tnau.ac.in",
        "document_identifier": "TNAU-AGRI-PULSES-2023",
        "publication_year": 2023,
        "verification_status": "VERIFIED",
        "source_scope": "STATE",
    },
    {
        "id": "src_demo_fallback",
        "tier": "DEVELOPMENT_DEMO",
        "organization": "SmartKisan Development Baseline Data",
        "source_title": "Development Fallback Agronomic Estimates",
        "url": None,
        "document_identifier": "SK-DEMO-2026",
        "publication_year": 2026,
        "verification_status": "DEVELOPMENT_DEMO",
        "source_scope": "DEVELOPMENT_DEMO",
    },
]

# 2. District to Agro-Climatic Zone Mapping
SEED_DISTRICT_ZONE_MAP = {
    # 1. Upper Gangetic Plain Zone (UP)
    ("Uttar Pradesh", "Ghaziabad"): "Upper Gangetic Plain Zone",
    ("Uttar Pradesh", "Meerut"): "Upper Gangetic Plain Zone",
    ("Uttar Pradesh", "Agra"): "Upper Gangetic Plain Zone",
    ("Uttar Pradesh", "Kanpur"): "Upper Gangetic Plain Zone",
    ("Uttar Pradesh", "Lucknow"): "Upper Gangetic Plain Zone",

    # 2. Middle Gangetic Plain Zone (UP East & Bihar)
    ("Uttar Pradesh", "Gorakhpur"): "Middle Gangetic Plain Zone",
    ("Uttar Pradesh", "Varanasi"): "Middle Gangetic Plain Zone",
    ("Bihar", "Patna"): "Middle Gangetic Plain Zone",
    ("Bihar", "Gaya"): "Middle Gangetic Plain Zone",
    ("Bihar", "Muzaffarpur"): "Middle Gangetic Plain Zone",

    # 3. Trans-Gangetic Plain Zone (Punjab, Haryana, Delhi, Chandigarh)
    ("Punjab", "Ludhiana"): "Trans-Gangetic Plain Zone",
    ("Punjab", "Amritsar"): "Trans-Gangetic Plain Zone",
    ("Punjab", "Jalandhar"): "Trans-Gangetic Plain Zone",
    ("Punjab", "Patiala"): "Trans-Gangetic Plain Zone",
    ("Punjab", "Bhatinda"): "Trans-Gangetic Plain Zone",
    ("Haryana", "Karnal"): "Trans-Gangetic Plain Zone",
    ("Haryana", "Ambala"): "Trans-Gangetic Plain Zone",
    ("Haryana", "Hisar"): "Trans-Gangetic Plain Zone",
    ("Haryana", "Rohtak"): "Trans-Gangetic Plain Zone",
    ("Delhi", "New Delhi"): "Trans-Gangetic Plain Zone",
    ("Chandigarh", "Chandigarh"): "Trans-Gangetic Plain Zone",

    # 4. East Coast Plains and Hills Zone (Tamil Nadu, Andhra Pradesh, Odisha, Puducherry)
    ("Tamil Nadu", "Thanjavur"): "East Coast Plains and Hills Zone",
    ("Tamil Nadu", "Chennai"): "East Coast Plains and Hills Zone",
    ("Tamil Nadu", "Cuddalore"): "East Coast Plains and Hills Zone",
    ("Andhra Pradesh", "Guntur"): "East Coast Plains and Hills Zone",
    ("Andhra Pradesh", "Krishna"): "East Coast Plains and Hills Zone",
    ("Odisha", "Puri"): "East Coast Plains and Hills Zone",
    ("Puducherry", "Puducherry"): "East Coast Plains and Hills Zone",

    # 5. Southern Plateau and Hills Zone (TN Inland, AP Inland, Telangana, Karnataka)
    ("Tamil Nadu", "Madurai"): "Southern Plateau and Hills Zone",
    ("Tamil Nadu", "Coimbatore"): "Southern Plateau and Hills Zone",
    ("Tamil Nadu", "Trichy"): "Southern Plateau and Hills Zone",
    ("Tamil Nadu", "Salem"): "Southern Plateau and Hills Zone",
    ("Telangana", "Hyderabad"): "Southern Plateau and Hills Zone",
    ("Telangana", "Warangal"): "Southern Plateau and Hills Zone",
    ("Karnataka", "Bengaluru"): "Southern Plateau and Hills Zone",
    ("Karnataka", "Mysuru"): "Southern Plateau and Hills Zone",

    # 6. Western Plateau and Hills Zone (Maharashtra Inland, MP South)
    ("Maharashtra", "Pune"): "Western Plateau and Hills Zone",
    ("Maharashtra", "Nashik"): "Western Plateau and Hills Zone",
    ("Maharashtra", "Nagpur"): "Western Plateau and Hills Zone",
    ("Madhya Pradesh", "Indore"): "Western Plateau and Hills Zone",

    # 7. West Coast Plains and Ghats Zone (Kerala, Goa, Karnataka Coastal, Maharashtra Coastal, Daman & Diu)
    ("Kerala", "Wayanad"): "West Coast Plains and Ghats Zone",
    ("Kerala", "Palakkad"): "West Coast Plains and Ghats Zone",
    ("Kerala", "Idukki"): "West Coast Plains and Ghats Zone",
    ("Goa", "North Goa"): "West Coast Plains and Ghats Zone",
    ("Dadra and Nagar Haveli and Daman and Diu", "Daman"): "West Coast Plains and Ghats Zone",

    # 8. Gujarat Plains and Hills Zone (Gujarat)
    ("Gujarat", "Ahmedabad"): "Gujarat Plains and Hills Zone",
    ("Gujarat", "Surat"): "Gujarat Plains and Hills Zone",
    ("Gujarat", "Rajkot"): "Gujarat Plains and Hills Zone",

    # 9. Central Plateau and Hills Zone (MP, Rajasthan East)
    ("Madhya Pradesh", "Bhopal"): "Central Plateau and Hills Zone",
    ("Madhya Pradesh", "Gwalior"): "Central Plateau and Hills Zone",
    ("Rajasthan", "Jaipur"): "Central Plateau and Hills Zone",
    ("Rajasthan", "Udaipur"): "Central Plateau and Hills Zone",

    # 10. Western Dry Region (Rajasthan West)
    ("Rajasthan", "Jodhpur"): "Western Dry Region",
    ("Rajasthan", "Bikaner"): "Western Dry Region",
    ("Rajasthan", "Jaisalmer"): "Western Dry Region",

    # 11. Western Himalayan Region (J&K, Ladakh, Himachal Pradesh, Uttarakhand)
    ("Jammu and Kashmir", "Srinagar"): "Western Himalayan Region",
    ("Jammu and Kashmir", "Jammu"): "Western Himalayan Region",
    ("Ladakh", "Leh"): "Western Himalayan Region",
    ("Himachal Pradesh", "Shimla"): "Western Himalayan Region",
    ("Uttarakhand", "Dehradun"): "Western Himalayan Region",

    # 12. Eastern Himalayan Region (Assam, Sikkim, Meghalaya, Nagaland, Manipur, Mizoram, Tripura, Arunachal Pradesh)
    ("Assam", "Guwahati"): "Eastern Himalayan Region",
    ("Sikkim", "Gangtok"): "Eastern Himalayan Region",
    ("Meghalaya", "Shillong"): "Eastern Himalayan Region",
    ("Nagaland", "Kohima"): "Eastern Himalayan Region",
    ("Manipur", "Imphal"): "Eastern Himalayan Region",
    ("Mizoram", "Aizawl"): "Eastern Himalayan Region",
    ("Tripura", "Agartala"): "Eastern Himalayan Region",
    ("Arunachal Pradesh", "Itanagar"): "Eastern Himalayan Region",

    # 13. Lower Gangetic Plain Zone (West Bengal)
    ("West Bengal", "Kolkata"): "Lower Gangetic Plain Zone",
    ("West Bengal", "Burdwan"): "Lower Gangetic Plain Zone",

    # 14. Eastern Plateau and Hills Zone (Jharkhand, Chhattisgarh, Odisha Inland)
    ("Jharkhand", "Ranchi"): "Eastern Plateau and Hills Zone",
    ("Chhattisgarh", "Raipur"): "Eastern Plateau and Hills Zone",

    # 15. The Islands Zone (Andaman & Nicobar Islands, Lakshadweep)
    ("Andaman and Nicobar Islands", "Port Blair"): "The Islands Zone",
    ("Lakshadweep", "Kavaratti"): "The Islands Zone",
}

# 3. Master Crop Catalog
SEED_CROP_CATALOG = [
    {
        "code": "summer_moong",
        "crop_name": "Summer Moong",
        "scientific_name": "Vigna radiata",
        "hindi_name": "समर मूंग",
        "category": "Pulse",
        "growth_habit": "Annual",
        "is_gap_candidate": True,
        "min_duration_days": 55,
        "max_duration_days": 65,
        "water_requirement": "Low",
        "season": "Zaid / Summer",
        "is_legume": True,
        "expected_yield_qtl_per_acre": 4.5,
        "net_profit_per_acre_min": 22000,
        "net_profit_per_acre_max": 30000,
        "investment_per_acre": 6500,
        "market_price_per_quintal": 8550,
        "description": "Short-duration pulse crop ideal for gap windows between Rabi Wheat and Kharif Paddy.",
        "active": True,
        "verification_status": "VERIFIED",
    },
    {
        "code": "summer_urad",
        "crop_name": "Summer Urad",
        "scientific_name": "Vigna mungo",
        "hindi_name": "समर उड़द",
        "category": "Pulse",
        "growth_habit": "Annual",
        "is_gap_candidate": True,
        "min_duration_days": 60,
        "max_duration_days": 70,
        "water_requirement": "Low",
        "season": "Zaid / Summer",
        "is_legume": True,
        "expected_yield_qtl_per_acre": 4.0,
        "net_profit_per_acre_min": 18000,
        "net_profit_per_acre_max": 25000,
        "investment_per_acre": 7000,
        "market_price_per_quintal": 7400,
        "description": "Short-duration leguminous gap pulse crop.",
        "active": True,
        "verification_status": "VERIFIED",
    },
    {
        "code": "cowpea",
        "crop_name": "Cowpea (Lobia)",
        "scientific_name": "Vigna unguiculata",
        "hindi_name": "लोबिया / बोड़ा",
        "category": "Pulse / Vegetable",
        "growth_habit": "Annual",
        "is_gap_candidate": True,
        "min_duration_days": 50,
        "max_duration_days": 60,
        "water_requirement": "Low-Moderate",
        "season": "Zaid / Summer",
        "is_legume": True,
        "expected_yield_qtl_per_acre": 5.0,
        "net_profit_per_acre_min": 15000,
        "net_profit_per_acre_max": 22000,
        "investment_per_acre": 6000,
        "market_price_per_quintal": 5500,
        "description": "Dual-purpose vegetable and green manure leguminous pulse crop.",
        "active": True,
        "verification_status": "VERIFIED",
    },
    {
        "code": "summer_sesame",
        "crop_name": "Summer Sesame (Til)",
        "scientific_name": "Sesamum indicum",
        "hindi_name": "समर तिल",
        "category": "Oilseed",
        "growth_habit": "Annual",
        "is_gap_candidate": True,
        "min_duration_days": 75,
        "max_duration_days": 85,
        "water_requirement": "Low",
        "season": "Zaid / Summer",
        "is_legume": False,
        "expected_yield_qtl_per_acre": 3.0,
        "net_profit_per_acre_min": 20000,
        "net_profit_per_acre_max": 28000,
        "investment_per_acre": 5500,
        "market_price_per_quintal": 14500,
        "description": "High-value short duration oilseed for extended gap windows (75+ days).",
        "active": True,
        "verification_status": "PENDING_VERIFICATION",
    },
    {
        "code": "fodder_maize",
        "crop_name": "Fodder Maize",
        "scientific_name": "Zea mays (Fodder)",
        "hindi_name": "चारा मक्का",
        "category": "Fodder",
        "growth_habit": "Annual",
        "is_gap_candidate": True,
        "min_duration_days": 45,
        "max_duration_days": 55,
        "water_requirement": "Moderate",
        "season": "Zaid / Summer",
        "is_legume": False,
        "expected_yield_qtl_per_acre": 150.0,
        "net_profit_per_acre_min": 12000,
        "net_profit_per_acre_max": 18000,
        "investment_per_acre": 5000,
        "market_price_per_quintal": 220,
        "description": "Ultra-short green fodder crop for livestock farmers.",
        "active": True,
        "verification_status": "VERIFIED",
    },
    # Non-Gap Candidates (Main Crops Excluded from Gap Recommendations)
    {
        "code": "paddy",
        "crop_name": "Paddy / Rice (Main Crop)",
        "scientific_name": "Oryza sativa",
        "hindi_name": "धान (मुख्य फसल)",
        "category": "Cereal",
        "growth_habit": "Annual",
        "is_gap_candidate": False,
        "min_duration_days": 120,
        "max_duration_days": 150,
        "water_requirement": "High",
        "season": "Kharif",
        "is_legume": False,
        "expected_yield_qtl_per_acre": 22.0,
        "net_profit_per_acre_min": 25000,
        "net_profit_per_acre_max": 38000,
        "investment_per_acre": 15000,
        "market_price_per_quintal": 2183,
        "description": "Main Kharif cereal crop (Excluded from short gap recommendations).",
        "active": True,
        "verification_status": "VERIFIED",
    },
    {
        "code": "sugarcane",
        "crop_name": "Sugarcane",
        "scientific_name": "Saccharum officinarum",
        "hindi_name": "गन्ना (दीर्घकालिक फसल)",
        "category": "Cash Crop",
        "growth_habit": "Perennial",
        "is_gap_candidate": False,
        "min_duration_days": 300,
        "max_duration_days": 365,
        "water_requirement": "Very High",
        "season": "Perennial",
        "is_legume": False,
        "expected_yield_qtl_per_acre": 350.0,
        "net_profit_per_acre_min": 50000,
        "net_profit_per_acre_max": 80000,
        "investment_per_acre": 30000,
        "market_price_per_quintal": 355,
        "description": "Long duration cash crop (Excluded from short gap recommendations).",
        "active": True,
        "verification_status": "VERIFIED",
    },
]

# 4. Multi-State Regional Crop Calendar Knowledge (With Location Scope & Verification Status)
SEED_REGIONAL_CALENDAR = [
    {
        "state_name": "Uttar Pradesh",
        "district_name": "Ghaziabad",
        "agro_climatic_zone": "Upper Gangetic Plain Zone",
        "crop_name": "Summer Moong",
        "sowing_start_month": 3,
        "sowing_end_month": 5,
        "harvest_start_month": 5,
        "harvest_end_month": 7,
        "regional_suitability": "High",
        "irrigation_condition": "Tube well",
        "confidence_weight": 0.95,
        "source": "ICAR-IIPR Kanpur / UP Agri Dept Guidelines",
        "source_id": "src_icar_iipr",
        "source_scope": "DISTRICT",
        "verification_status": "VERIFIED",
        "active": True,
    },
    {
        "state_name": "Uttar Pradesh",
        "district_name": "Ghaziabad",
        "agro_climatic_zone": "Upper Gangetic Plain Zone",
        "crop_name": "Summer Urad",
        "sowing_start_month": 3,
        "sowing_end_month": 4,
        "harvest_start_month": 5,
        "harvest_end_month": 6,
        "regional_suitability": "High",
        "irrigation_condition": "Tube well",
        "confidence_weight": 0.90,
        "source": "UP State Agri Dept Zaid Guidelines",
        "source_id": "src_up_agri",
        "source_scope": "DISTRICT",
        "verification_status": "VERIFIED",
        "active": True,
    },
    {
        "state_name": "Punjab",
        "district_name": "Ludhiana",
        "agro_climatic_zone": "Trans-Gangetic Plain Zone",
        "crop_name": "Summer Moong",
        "sowing_start_month": 3,
        "sowing_end_month": 4,
        "harvest_start_month": 5,
        "harvest_end_month": 6,
        "regional_suitability": "High",
        "irrigation_condition": "Tube well",
        "confidence_weight": 0.98,
        "source": "Punjab Agricultural University (PAU), Ludhiana Farm Advisory",
        "source_id": "src_pau_ludhiana",
        "source_scope": "DISTRICT",
        "verification_status": "VERIFIED",
        "active": True,
    },
    {
        "state_name": "Punjab",
        "district_name": "Ludhiana",
        "agro_climatic_zone": "Trans-Gangetic Plain Zone",
        "crop_name": "Fodder Maize",
        "sowing_start_month": 3,
        "sowing_end_month": 5,
        "harvest_start_month": 5,
        "harvest_end_month": 7,
        "regional_suitability": "High",
        "irrigation_condition": "Canal",
        "confidence_weight": 0.90,
        "source": "PAU Ludhiana Package of Practices",
        "source_id": "src_pau_ludhiana",
        "source_scope": "DISTRICT",
        "verification_status": "VERIFIED",
        "active": True,
    },
    {
        "state_name": "Tamil Nadu",
        "district_name": "Thanjavur",
        "agro_climatic_zone": "East Coast Plains and Hills Zone",
        "crop_name": "Cowpea (Lobia)",
        "sowing_start_month": 1,
        "sowing_end_month": 3,
        "harvest_start_month": 3,
        "harvest_end_month": 5,
        "regional_suitability": "High",
        "irrigation_condition": "Canal",
        "confidence_weight": 0.95,
        "source": "TNAU Agritech Rice Fallow Pulses Protocol",
        "source_id": "src_tnau",
        "source_scope": "DISTRICT",
        "verification_status": "VERIFIED",
        "active": True,
    },
    {
        "state_name": "Haryana",
        "district_name": None,
        "agro_climatic_zone": "Trans-Gangetic Plain Zone",
        "crop_name": "Summer Moong",
        "sowing_start_month": 3,
        "sowing_end_month": 4,
        "harvest_start_month": 5,
        "harvest_end_month": 6,
        "regional_suitability": "High",
        "irrigation_condition": "All",
        "confidence_weight": 0.85,
        "source": "Trans-Gangetic Plain ICAR Regional Agronomy Guide",
        "source_id": "src_icar_iipr",
        "source_scope": "AGRO_CLIMATIC_ZONE",
        "verification_status": "VERIFIED",
        "active": True,
    },
]

# 5. Crop Nutrient Profiles (Cautious Agronomic Framing - NOT Measured Soil Tests)
SEED_NUTRIENT_PROFILES = [
    {
        "crop_name": "Wheat",
        "nitrogen_effect": "Relatively high nitrogen extraction from cereal harvest",
        "phosphorus_effect": "Moderate phosphorus removal",
        "potassium_effect": "Moderate potassium removal",
        "organic_matter_effect": "Low residual organic matter if stubble is removed",
        "is_legume": False,
        "rotation_notes": "Wheat leaves soil in need of nitrogen replenishment; ideal candidate for legume rotation.",
        "source": "ICAR Agronomy Handbook",
        "verification_status": "VERIFIED",
    },
    {
        "crop_name": "Mustard",
        "nitrogen_effect": "Moderate nitrogen removal",
        "phosphorus_effect": "High phosphorus & sulphur uptake",
        "potassium_effect": "Moderate potassium removal",
        "organic_matter_effect": "Root biomass adds minor organic matter",
        "is_legume": False,
        "rotation_notes": "Mustard consumes soil sulphur; short pulse rotation helps rebuild soil structure.",
        "source": "ICAR-DRMR Bharatpur Baseline Guide",
        "verification_status": "VERIFIED",
    },
    {
        "crop_name": "Potato",
        "nitrogen_effect": "High nutrient removal, moderate residual N from fertilizer application",
        "phosphorus_effect": "High residual phosphorus in topsoil",
        "potassium_effect": "Heavy potassium depletion",
        "organic_matter_effect": "Favorable soil tilth remaining after harvest",
        "is_legume": False,
        "rotation_notes": "Heavy feeder crop; short legume gap crop utilizes residual P and restores N.",
        "source": "ICAR-CPRI Shimla Technical Bulletin",
        "verification_status": "VERIFIED",
    },
]

# 6. Crop Rotation Compatibility Matrix
SEED_COMPATIBILITY_MATRIX = [
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Summer Moong",
        "compatibility_status": "Compatible",
        "rotation_notes": "Excellent cereal-legume rotation. Moong fixes atmospheric nitrogen for subsequent Kharif paddy.",
        "source": "ICAR Agronomy Guidelines",
        "verification_status": "VERIFIED",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Summer Urad",
        "compatibility_status": "Compatible",
        "rotation_notes": "Favorable cereal-legume sequence with good soil health restoration.",
        "source": "ICAR Agronomy Guidelines",
        "verification_status": "VERIFIED",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Cowpea (Lobia)",
        "compatibility_status": "Compatible",
        "rotation_notes": "Short duration legume ideal after wheat harvest.",
        "source": "ICAR Agronomy Guidelines",
        "verification_status": "VERIFIED",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Summer Sesame (Til)",
        "compatibility_status": "Compatible",
        "rotation_notes": "Suitable non-legume cash crop after wheat if gap window is 75+ days.",
        "source": "ICAR Agronomy Guidelines",
        "verification_status": "VERIFIED",
    },
    {
        "previous_crop": "Wheat",
        "candidate_crop": "Fodder Maize",
        "compatibility_status": "Caution",
        "rotation_notes": "Cereal after cereal requires additional nitrogen management.",
        "source": "ICAR Agronomy Guidelines",
        "verification_status": "VERIFIED",
    },
]